### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#103]
Now we have more people making PRs good to have checks integrated w github

**Comment by kltm** [comment]
Added the hook for Jenkins; is there anything else needed here?

What is the policy for the split between the two? Integration is nice, but we already have a separate build pipeline around Jenkins (that's also not tied to github).

@hdietze

**Comment by cmungall** [comment]
Failed to catch my attempt to break the yaml with a fake PR

<img width="902" alt="screen shot 2015-09-14 at 1 56 42 pm" src="https://cloud.githubusercontent.com/assets/50745/9861648/75091dd0-5ae8-11e5-9801-fa29a0ea5411.png">

**Comment by cmungall** [comment]
For example of where travis is beneficial: http://obofoundry.github.io/faq/how-do-i-edit-metadata.html

**Comment by kltm** [comment]
Ah, so the idea is to check PRs before hitting master. There is little added utility if people are working directly on master, but with people working on the data with a PR workflow, that makes sense.

Naturally, there is a plugin, but it looks like it starts to push again Jenkins-ness. I think what I'm a little uncomfortable with here is that there are now two places to watch unit tests: Jenkins (as the checking is naturally part of the build and publish pipeline) and Travis (part of aggressive testing)--both good, but overlapping; and given the confusion on other projects about what's where, I'm a little worried about adding new bits and bobs.

One way to find out though...

**Comment by kltm** [comment]
A few notes:

* Working with the underlying (apparently deb-based) system to bring in kwalify didn't work as expected, so had to fall back to doing it the "ruby" way
* It all seems to be very much geared towards one language per project, which will get irritating real fast as a lot of our stuff is mixed and I was going to add node stuff as well to these tests (in addition to kwalify--ruby)
* The comments from monarch about some of the testing environment confusion makes a sense now--the jenkins and travis ones will need to be maintained separately (until there is an uber-service for CI^2)

**Comment by cmungall** [comment]
Just curious as to why the ruby kwalify was chosen over the python one

not a big deal but the ruby one forces us into these contortions:

```
  - kwalify -E -f metadata/users.schema.yaml metadata/users.yaml 2>&1 | tee out.log && grep 'INVALID\|ERROR' out.log; test $? -ne 0
```

if we implement this more widely for other repos it would be nice to have a simpler pattern

**Comment by kltm** [comment]
Because kwalify is a ruby package, we already have the schemas for it, and has been used since before travis (which is the one having the issues catching the errors). However, kwalify *is* older and showing it's age--I'd be happy to have a migration to something else, python or JS, preferably to some generally agreed standard.

**Comment by cmungall** [comment]
Just to be clear. Not talking about changing the schema (unless there is reason too). Confusingly, `kwalify` is the name of both the ruby script and the general meta-schema, which has an alternate python implementation AFAICT

**Comment by kltm** [comment]
I did not know that. Huh.

There is actually another reason for the standard ruby kwalify--it is a standard package on ubuntu, which is pretty nice for various reasons. Looking at the python version, I'd be less that enthused to make such a wobbly jump: AFAICT, it's a port of the brutally old *java* version, rather than the less old ruby version, which is weird. Also, it is not a standard package.

Is this really a standard meta-schema, or is it just an implementation by a few port related packages?

That said, there are several things that I'd like to be able to do that are not supported by the current schema setup (unknown about the pykwalify).
