### ISSUE TITLE
users.yaml file has same md5sum email for multiple users

### ISSUE THREAD

**Issue by mugitty** [geneontology/go-site#119]
users.yaml file has identical md5 email for multiple users (Amanda Mackie and Anushya Muruganujan)

**Comment by kltm** [comment]
Very bad. Thank you for reporting.

**Comment by kltm** [comment]
Vanishingly unlikely that it's an actual collision, will track down the original email addresses with @mugitty 's help over email.

**Comment by kltm** [comment]
After discussion with @mugitty, the dupes were likely copy-paste errors and the different numbers due to a quirk in how the md5sums are generated (see https://github.com/geneontology/go-site/blob/master/metadata/README.md#generating-md5-hashes for details). Decreasing level.

**Comment by kltm** [comment]
@mugitty Could you ensure that you have the right address for yourself in there, and then, if you don't have the correct one for Amanda (e.g. it is a dupe), go ahead and remove her email-md5 (it should be an optional field)? Make sure to tag this item so we understand the changes in the future.

**Comment by mugitty** [comment]
I have removed the email-md5 for Amanda.

**Comment by kltm** [comment]
Thank you. 
In general, it's good to close or reference the ticket from within the commit comment so that we can tie a specific diff to an issue for future tracking. I mention this since the change you pushed is not entirely clear (https://github.com/geneontology/go-site/commit/d1a0a5548cc764a8dc39894f6a14063e9eb5567a).

**Comment by kltm** [comment]
Cheers!

**Comment by kltm** [comment]
Revisiting this again while generating new users, I'm unsure about the "echo"/"echo -n" issue, and have reverted the instructions (using "echo -n" again). It may be that there was another hiccup elsewhere (version?) and I diagnosed it wrong. (tagging on @cmungall since we chatted about this earlier today as well).
