### ISSUE TITLE
should taxon constraints apply to NOT annotations?

### ISSUE THREAD

**Issue by mah11** [geneontology/go-site#1256]
We're getting this warning from the annotation QC checks:

	WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- PomBase SPBC19C2.02 pmt1 NOT GO:0009008 PMID:8636983 IDA F tRNA (cytosine-5-)-methyltransferase Pmt1 dnmt2 protein taxon:4896 20050708 PomBase

GO:0009008 is indeed flagged as "never in Schizosaccharomyces pombe" ... but the annotation has the NOT qualifier. The point of the paper is to show that pombe Pmt1 doesn't have this activity (it may well be a big chunk of the evidence behind the taxon constraint). Can we ... er, not make this annotation?

I put the ticket in this tracker because it seems like the taxon checks could, and probably should, permit "NOT" annotations to terms that don't apply to the gp's taxon. Otherwise we lose information that a curator thought worth capturing, and that supports the taxon constraints themselves.

**Comment by pgaudet** [comment]
The current behavior looks OK to me 
@vanaukenk @ukemi @thomaspd What do you think? 

Should we bring this up on an annotation call ?

**Comment by mah11** [comment]
> The current behavior looks OK to me

How so?

A "positive" annotation to a never-in-this-taxon term should be flagged, but why is it correct to disallow an explicit NOT annotation?

**Comment by vanaukenk** [comment]
I think this would be a good example to discuss on an annotation call to clarify our use of 'NOT' because it raises the issue of what it means to 'expect' that a gene product might have an activity based on sequence analysis.

My reading of some relevant abstracts is that Pmt1 contains a non-consensus residue in the active site that prevents it from acting on DNA as a substrate, but allows it to act on tRNA as a substrate.

If there's a non-consensus residue in an active site, should we 'expect' a gene product to have the activity, and how far should curators go to analyze or address that question?

**Comment by ukemi** [comment]
But in general, I completely agree with @mah11.

**Comment by pgaudet** [comment]
Discussion with @thomaspd 
We agree that although this is a little unintuitive, it makes sense to allow it.

**Comment by pgaudet** [comment]
Added this to the modification requests for gorule-0000013

https://github.com/geneontology/go-site/issues/882
