### ISSUE TITLE
Blocking issues with EcoCyc GAF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1426]
Hello,

The Ecoli GAF (https://ecoliwiki.org/gaf/gene_association.ecocyc.gz) has a number of issues, some of which result in a large drop in the number of E. coli annotations. Here are the main problems failing our checks: 

**EcoWiki data**

1. Invalid qualifier: “Contributes_to"  should be “contributes_to"
(this one is not a new issue, but should be fixed) 
Affects about ~250 annotations

2. gorule-0000027 Each identifier in GAF is valid
~ 5000 errors 
UniProtKB should be changed to UniProt

3. IEAs are > 1 year old (this will not be filtered yet, but the IEA pipeline should be re-run soon; or the data obtained from GOA)

4. Deprecated GO_REFs are not allowed (this will not be filtered yet, but it's an easy fix) 
Affects about ~10,000 annotations: 

GO_REF:0000039 -> Change to GO_REF:0000044
GO_REF:0000037 -> Change to GO_REF:0000043

**CollecTF data:** 

1. Unsupported evidence codes
Problem | Replacement | Number of occurrences
ECO:0005525 	Should be replaced by ECO:0000273	504 uses
ECO:0005664 	cannot find	13 uses

2. IPI annotations with no ‘with’ data 
GO:0000976	transcription regulatory region sequence-specific DNA binding
GO:0001130	replaced by GO:0003700 
DNA-binding transcription factor activity
GO:0001216	DNA-binding transcription activator activity
GO:0001217	DNA-binding transcription repressor activity
GO:0032993	protein-DNA complex
GO:0043565	sequence-specific DNA binding
-> Need to either add’ with’ data or change the evidence code to IDA. 

If changes cannot be made this week, we'll use the file from the previous version, until the fixes are made. 

Thanks, Pascale

**Comment by keseler** [comment]
We import the automatic mappings from GOA for each EcoCyc release; they should not be more than a year old on our end.  I do not know which release version of EcoCyc is in the EcoliWiki file; it's possible that it is from an older release.
I'm about to take a look at some of the other problems, now that I can actually work from home (quite an ordeal to get that up and running).

**Comment by keseler** [comment]
A number of evidence class errors are coming from EcoCyc, what seems to be originating as EV-AS (author statement) here and should be mapped to ECO:0000204.  I frankly have no idea where the mapping from our evidence codes to ECO happens; if here, we'll fix it.  I'll try to find out.

**Comment by keseler** [comment]
EcoCyc EV-AS-HYPO should be mapped to ECO:0000034.

**Comment by kltm** [comment]
As a temporary bypass for this issue, we will be using http://release.geneontology.org/2020-02-26/products/annotations/ecocyc-src.gaf.gz as a source for the next `release` run.

**Comment by kltm** [comment]
From conversation with @pgaudet, we'll  move forward with this configuration for the moment.

**Comment by keseler** [comment]
Re. "WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check" - these seem to be mostly transporters with transport GO terms, and I don't understand what would be not taxon-appropriate about those annotations.  @pgaudet could you clarify?

**Comment by pgaudet** [comment]
I don't understand either why GO:0015813 L-glutamate transmembrane transport gives a taxon error. In QuickGO and in out taxon constraints file I see no reason why this one would fail. 

@dougli1sqrd Can you please have a look ?

**Comment by mah11** [comment]
It's the CHEBI roles thing - some of the transported substances have role classifications that lead to taxon-restricted processes (I know because it affects a few PomBase annotations too).

**Comment by pgaudet** [comment]
I thought so, but the we would see it in QuickGO, wouldn't we ?

**Comment by balhoff** [comment]
Here is the explanation:

## [Nothing](http://www.w3.org/2002/07/owl#Nothing) EquivalentTo [L-glutamate transmembrane transport](http://purl.obolibrary.org/obo/GO_0015813) and ([in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Escherichia coli](http://purl.obolibrary.org/obo/NCBITaxon_562)) ##

  - [Unikonta](http://purl.obolibrary.org/obo/NCBITaxon_Union_0000024) SubClassOf [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759)
  - [L-glutamate transmembrane transport](http://purl.obolibrary.org/obo/GO_0015813) SubClassOf [neurotransmitter transport](http://purl.obolibrary.org/obo/GO_0006836)
  - [neurotransmitter transport](http://purl.obolibrary.org/obo/GO_0006836) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208)
  - [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) SubClassOf [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154)
  - [Escherichia](http://purl.obolibrary.org/obo/NCBITaxon_561) SubClassOf [Enterobacteriaceae](http://purl.obolibrary.org/obo/NCBITaxon_543)
  - [Gammaproteobacteria](http://purl.obolibrary.org/obo/NCBITaxon_1236) SubClassOf [Proteobacteria](http://purl.obolibrary.org/obo/NCBITaxon_1224)
  - [Enterobacteriaceae](http://purl.obolibrary.org/obo/NCBITaxon_543) SubClassOf [Enterobacterales](http://purl.obolibrary.org/obo/NCBITaxon_91347)
  - [Unikonta](http://purl.obolibrary.org/obo/NCBITaxon_Union_0000024) EquivalentTo [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154) or [Amoebozoa](http://purl.obolibrary.org/obo/NCBITaxon_554915)
  - [Proteobacteria](http://purl.obolibrary.org/obo/NCBITaxon_1224) SubClassOf [Bacteria](http://purl.obolibrary.org/obo/NCBITaxon_2)
  - [Escherichia coli](http://purl.obolibrary.org/obo/NCBITaxon_562) SubClassOf [Escherichia](http://purl.obolibrary.org/obo/NCBITaxon_561)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Bacteria](http://purl.obolibrary.org/obo/NCBITaxon_2) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759)
  - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [Enterobacterales](http://purl.obolibrary.org/obo/NCBITaxon_91347) SubClassOf [Gammaproteobacteria](http://purl.obolibrary.org/obo/NCBITaxon_1236)

**Comment by ukemi** [comment]
Yep. ChEBI roles.

**Comment by balhoff** [comment]
Here is a better explanation that makes that clear. I had to do the first one using go-gaf, because we don't have E. coli in the editor file. But go-gaf has some inferences already computed.

## [Nothing](http://www.w3.org/2002/07/owl#Nothing) EquivalentTo [L-glutamate transmembrane transport](http://purl.obolibrary.org/obo/GO_0015813) and ([in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Bacteria](http://purl.obolibrary.org/obo/NCBITaxon_2)) ##

  - [carbonyl compound](http://purl.obolibrary.org/obo/CHEBI_36586) SubClassOf [organic oxo compound](http://purl.obolibrary.org/obo/CHEBI_36587)
  - [organic oxo compound](http://purl.obolibrary.org/obo/CHEBI_36587) SubClassOf [organic molecule](http://purl.obolibrary.org/obo/CHEBI_72695)
  - [L-glutamic acid](http://purl.obolibrary.org/obo/CHEBI_16015) SubClassOf [glutamine family amino acid](http://purl.obolibrary.org/obo/CHEBI_24318)
  - [polyatomic entity](http://purl.obolibrary.org/obo/CHEBI_36357) SubClassOf [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367)
  - [substance with neurotransmitter role](http://purl.obolibrary.org/obo/GOCHE_25512) EquivalentTo [chemical entity](http://purl.obolibrary.org/obo/CHEBI_24431) and ([has role](http://purl.obolibrary.org/obo/RO_0000087) some [neurotransmitter](http://purl.obolibrary.org/obo/CHEBI_25512))
  - [acidic amino acid transport](http://purl.obolibrary.org/obo/GO_0015800) SubClassOf [amino acid transport](http://purl.obolibrary.org/obo/GO_0006865)
  - [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) SubClassOf [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154)
  - [carboxylic acid](http://purl.obolibrary.org/obo/CHEBI_33575) SubClassOf [carbonyl compound](http://purl.obolibrary.org/obo/CHEBI_36586)
  - [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [L-glutamic acid](http://purl.obolibrary.org/obo/CHEBI_16015) EquivalentTo [transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [L-glutamate(1-)](http://purl.obolibrary.org/obo/CHEBI_29985)
  - [alpha-amino acid](http://purl.obolibrary.org/obo/CHEBI_33704) SubClassOf [amino acid](http://purl.obolibrary.org/obo/CHEBI_33709)
  - [L-glutamate transmembrane transport](http://purl.obolibrary.org/obo/GO_0015813) EquivalentTo [acidic amino acid transport](http://purl.obolibrary.org/obo/GO_0015800) and ([transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [L-glutamate(1-)](http://purl.obolibrary.org/obo/CHEBI_29985)) and ([results in transport across](http://purl.obolibrary.org/obo/RO_0002342) some [membrane](http://purl.obolibrary.org/obo/GO_0016020))
  - [amino acid transport](http://purl.obolibrary.org/obo/GO_0006865) EquivalentTo [transport](http://purl.obolibrary.org/obo/GO_0006810) and ([transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [amino acid](http://purl.obolibrary.org/obo/CHEBI_33709))
  - [glutamine family amino acid](http://purl.obolibrary.org/obo/CHEBI_24318) SubClassOf [L-alpha-amino acid](http://purl.obolibrary.org/obo/CHEBI_15705)
  - [Opisthokonta](http://purl.obolibrary.org/obo/NCBITaxon_33154) SubClassOf [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759)
  - [only_in_taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [amino acid](http://purl.obolibrary.org/obo/CHEBI_33709) SubClassOf [carboxylic acid](http://purl.obolibrary.org/obo/CHEBI_33575)
  - [neurotransmitter transport](http://purl.obolibrary.org/obo/GO_0006836) SubClassOf [only_in_taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208)
  - [molecule](http://purl.obolibrary.org/obo/CHEBI_25367) SubClassOf [polyatomic entity](http://purl.obolibrary.org/obo/CHEBI_36357)
  - [molecular entity](http://purl.obolibrary.org/obo/CHEBI_23367) SubClassOf [chemical entity](http://purl.obolibrary.org/obo/CHEBI_24431)
  - [neurotransmitter transport](http://purl.obolibrary.org/obo/GO_0006836) EquivalentTo [transport](http://purl.obolibrary.org/obo/GO_0006810) and ([transports or maintains localization of](http://purl.obolibrary.org/obo/RO_0002313) some [substance with neurotransmitter role](http://purl.obolibrary.org/obo/GOCHE_25512))
  - [L-alpha-amino acid](http://purl.obolibrary.org/obo/CHEBI_15705) SubClassOf [alpha-amino acid](http://purl.obolibrary.org/obo/CHEBI_33704)
  - [organic molecule](http://purl.obolibrary.org/obo/CHEBI_72695) SubClassOf [molecule](http://purl.obolibrary.org/obo/CHEBI_25367)
  - [L-glutamic acid](http://purl.obolibrary.org/obo/CHEBI_16015) SubClassOf [has role](http://purl.obolibrary.org/obo/RO_0000087) some [neurotransmitter](http://purl.obolibrary.org/obo/CHEBI_25512)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Bacteria](http://purl.obolibrary.org/obo/NCBITaxon_2) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759)

**Comment by pgaudet** [comment]
Thanks @balhoff @ukemi 

@krchristie Can you already remove that one ? This and ATP = drug are causing the most problems. 

Thanks, Pascale
