### ISSUE TITLE
GO Rule for handling unrealizable annotations as found out by gaferencer

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1485]
In Gaferencer, we can tell if an annotation conflicts with its extensions by gaferencer stating that the annotation is unrealizable. We know it's a taxon issue if the `taxonProblem` field in the output is false. 

Currently we have no rule (as far as I can tell) to deal with this possibility. Additionally, @dustine32 would like this implemented for making pristine GPADs for importing and for gocamgen. 

What should the results be of an annotation that fails this check? Should it be filtered? The extensions removed? @cmungall do you have thoughts?

(tagging @kltm and @pgaudet)

**Comment by kltm** [comment]
To summarize the options:
Conservative: "inconsistent" annotations are completely filtered with an error
Aggressive: extensions are removed with warning, remaining annotation accepted
Ostrich: Warn, but allow everything through

**Comment by dougli1sqrd** [comment]
I think if we can, the "aggressive" option above is best.

**Comment by dustine32** [comment]
Yeah the "aggressive" option is closest to how `gocamgen` was handling invalid extensions as required by @vanaukenk and @ukemi.

To clarify for multiple pipe-separated extensions, `gocamgen` was only removing the invalid extensions. Ex:
```
not_real_relation(GO:0000001)|occurs_in(CL:000001)
```
`not_real_relation` would be dropped but `occurs_in` would remain. And in the case that all extensions were invalid:
```
not_real_relation(GO:0000001)|occurs_in(FAKE:000001)
```
All extensions would be dropped and the primary, standard annotation would remain.

**Comment by kltm** [comment]
Touched bases with @cmungall, "aggressive" (as outlined by @dustine32 ) it is.

**Comment by pgaudet** [comment]
@dustine32 was this done for imports?

**Comment by pgaudet** [comment]
@kltm will clarify what this is about

**Comment by kltm** [comment]
Noting that `GROUP.gaferences.json` are produced in the "Mega-make" and used in "Temporary post filter" as `all.gaferences.json` for 
```
		    sh "make -f /opt/go-site/scripts/Makefile-gaf-reprocess all"
```

@dustine32 IIRC, this temp post filter step is exclusively about taxon constraints (and preventing reprocessing damage), correct?

**Comment by dustine32** [comment]
@kltm The temp post filter ended up being used to solve two things:
1. Check taxon constraints - https://github.com/geneontology/go-ontology/issues/20079
2. Repair GP2term relations in Noctua exported annotations - https://github.com/geneontology/pipeline/issues/220

For what remains to be done on this ticket here, I believe it is simply to somehow hook up the `all.gaferences.json` file to [GoRule58 in ontobio](https://github.com/biolink/ontobio/blob/8d5defc805d0d48017b149e5c6fde6ebb6f9f845/ontobio/io/qc.py#L692) rather than using `extensions_constraints.yaml`. It would be great to find an example annotation for which the current method (using `extensions_constraints.yaml`) is not working.

**Comment by kltm** [comment]
@pgaudet Considering the "somehow hook up the all.gaferences.json file to [GoRule58 in ontobio](https://github.com/biolink/ontobio/blob/8d5defc805d0d48017b149e5c6fde6ebb6f9f845/ontobio/io/qc.py#L692) rather than using extensions_constraints.yaml", I'd suggest that this would be slightly more complicated than a "low-hanging fruit", but still tractable for future work.

**Comment by pgaudet** [comment]
For reference: The rule is here: https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000058.md

**Comment by pgaudet** [comment]
@dustine32 
* gaferencer checks taxon constraints + other OWL consistency issues
* (maybe only taxon constraints are exported, but there are other checks being done) 
* the part of the rule checking extensions is only applied for imports of annotations into Noctua.
