### ISSUE TITLE
Proposed new front page for geneontology.org drupal

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#161]
from @thomaspd

[GO homepage Feb 2016.pptx](https://github.com/geneontology/go-site/files/141778/GO.homepage.Feb.2016.pptx)

**Comment by cmungall** [comment]
This proposal blends amigo and the site to some degree - for general comments on this refer to https://github.com/geneontology/amigo/issues/310

**Comment by monicacecilia** [comment]
Except for changing the 'Documentation' menu to be labeled with the word 'Help', these look like very useful suggestions.

**Comment by kltm** [comment]
Will make first raft of changes this evening when there is less traffic (no longer have active beta to play with).

**Comment by monicacecilia** [comment]
:+1:

**Comment by kltm** [comment]
I concur with @monicacecilia about the menu items. I'll also make a few changes to reflect the reality of current AmiGO limits.

**Comment by stuartmiyasato** [comment]
> Will make first raft of changes this evening when there is less traffic (no longer have active beta to play with).

@kltm Off-topic for this ticket, but would we want to clone the production site so we have a test/beta site to test these sorts of changes?

**Comment by kltm** [comment]
Hrm. I guess it depends on how annoying the clones are.
Currently, we have the battered http://beta.geneontology.org , which I am likely to poke a little; however, as the risk is fairly low and the fact that the exact css and block format is irritating to replay, I figured that working live was acceptably risky for the time save.
If there was a clone that could be worked on and then be made live, and it was not painful/time-consuming to do, that would be preferable. However, again, since there already snapshots, I considered the risk of live work not too bad. What does this look like on your end?

**Comment by kltm** [comment]
Looking at implementing some of this, there is currently no Mission Statement, right? Tagging @thomaspd.

**Comment by kltm** [comment]
In fact, I can't find the text for the two center boxes as well.

**Comment by thomaspd** [comment]
That’s correct.  Much of the text is new.  Can you get it from the Powerpoint, or do you need me to put the text in email/github?

**Comment by monicacecilia** [comment]
yikes, forgot this is MS-PPTX. 

@kltm here is the text: 

- for panel on the left "Gene Ontology (GO)": 

Gene Ontology: the framework for the model of biology.  The GO defines concepts/classes used to describe gene function, and relationships between these concepts.  It classifies functions along three aspects:
-molecular function: molecular activities of gene products
-cellular component: where gene products are active
-biological process: pathways and larger processes made up of the activities of multiple gene products. 

- for the panel on the middle-right "Annotations":

GO annotations: the model of biology.  Annotations are statements describing the functions of specific genes, using concepts in the Gene Ontology.  The simplest and most common annotation links one gene to one function, e.g. FZD4 + Wnt signaling pathway.  Each statement is based on a specified piece of evidence. 

- Mission statement: 

The mission of the GO Consortium is to develop an up-to-date, comprehensive, computational model of biological systems, from the molecular level to larger pathways, cellular and organism-level systems.  more.

**Comment by kltm** [comment]
Thank you @monicacecilia , but I think I'll need to take up @thomaspd offer on the full next body. For each of those, there is a "more" link at the end, implying that there is a longer body of text hiding somewhere. It's not in the ppx that is linked up top, at least not in a form I can access on my computer.

**Comment by monicacecilia** [comment]
Ok.  -- yes, I can't see any additional text on the PPTX file.

@thomaspd Do you already have additional text for these sections and that's why you added the 'More' link? Or were these only suggestions?

If more text is not already available, I suggest that for the time being the words 'More' could direct to 
http://geneontology.org/page/documentation for the panel on the left (GO), and http://geneontology.org/page/annotation for the panel on the right (Annotation).

**Comment by thomaspd** [comment]
The links are on the PowerPoint, but in a light gray so as to minimize clutter.  Here’s where they should link:
1. Left box (ontology) “more”: http://geneontology.org/page/ontology-documentation

**Comment by paolaroncaglia** [comment]
Link to the contributing to GO page

**Comment by kltm** [comment]
A first pass of changes are in. Some stuff has been punted for the time being as they were either digging too far into what the current template engine is will do before I start having to hand massage the CSS or due to navigation issues.

This is probably a good place to look and see where to move from here. Visually, there is not a lot going on anymore, but I'm not particularly sorry to see the ever-fiddly carousel go.

**Comment by monicacecilia** [comment]
Thanks!

One thing I just noticed. Since the "Tools Registry" was discontinued - and this page says so http://geneontology.org/page/go-tools-registry - I suggest that we should probably remove the hyperlinked text "Gene Ontology Tools" from this box: 

![screen shot 2016-03-07 at 11 44 09 am](https://cloud.githubusercontent.com/assets/1714621/13581100/26710b96-e45a-11e5-831d-20c7f9416f91.png)

I miss seeing a picture... however, I DO NOT miss the carousel. :bowtie:

**Comment by kltm** [comment]
From @thomaspd 
```
Oops, I missed a couple of things I had in my notes.

1. Please put a link to Other GOC Tools (linked to http://amigo.geneontology.org/amigo/software_list) under the Enrichment Analysis box on the home page.

2. Please put a link to GO User Stories (linked to http://geneontology.org/page/user-stories) under the Search Documentation box on the right side of the home page.
```

**Comment by kltm** [comment]
@monicacecilia removed

**Comment by kltm** [comment]
@thomaspd 
re-added user story link, with context
added tools link with context to first column

**Comment by monicacecilia** [comment]
Thank you! :tada:

**Comment by paolaroncaglia** [comment]
At the last editors call, Paul T made a few suggestions, summarised at the bottom of this agenda item:

http://wiki.geneontology.org/index.php/Ontology_meeting_2016-03-03#Follow-up:_strategy_for_ontology_requests

Making a note here so it's not forgotten, thanks.

**Comment by kltm** [comment]
@paolaroncaglia I'm not seeing the item(s). Could you copy any relevant parts for this ticket in?

**Comment by paolaroncaglia** [comment]
Sure. The summary is - Paul suggested we should make it clearer to users coming to the GO website that they can request new GO terms (or add them themselves if they are entitled to a TermGenie account) and/or suggest changes to existing terms. We have already have this FAQ, but it’s a bit ‘slim’:

http://geneontology.org/faq/how-can-i-suggest-new-go-terms

The action items resolved on were

1) Point to term request guidelines on GitHub from the FAQ above (https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md) 
(which I just did)

2) Link to the FAQ above from somewhere prominent on the GO website front page with some pithy text (Tanya suggested 'Help go grow’, for example). 
This would need one of you admin people please.

Any question let me or Paul know, thanks!

**Comment by kltm** [comment]
Now defunct with new pages and front page in progress...
