### ISSUE TITLE
export-lego-to-legacy Jenkins job is failing

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#168]
https://build.berkeleybop.org/view/GO/job/export-lego-to-legacy/ all red balls.

Null pointer exception in Minerva

**Comment by hdietze** [comment]
The Jenkins job is now working again. The export is now available as GAF and GPAD.
We now create specific files for taxon/mod groups.

**Comment by ukemi** [comment]
This is great. Where are the GAF files located?

**Comment by ukemi** [comment]
I found them in Jenkins, but will need a stable (PURL?) place to get them for import into our system. We will need to filter the models so that only ones that are not templates and are annotated as 'production' are used. 
Great progress!

**Comment by hdietze** [comment]
+1 Yes we **need** to create PURLs. Hosting files and hard coding Jenkins URLs is not stable nor future proof

The filter for production only models already exists. Only MGI has models marked as production and the preliminary URL:
https://build.berkeleybop.org/view/GO/job/export-lego-to-legacy/lastSuccessfulBuild/artifact/legacy/gaf/production/mgi.gaf

**Comment by ukemi** [comment]
Hi Heiko,

This is looking good.
I Just added another model to production. 
There are still a couple of small issues.

Ceacam20 Mmus-- These should just be Ceacam20 etc.
Any progress on making the annotations to folded terms (my columns might be off)?
Example #1 with regulation:
MGI	MGI:96537	Il10 Mmus		GO:0003674	PMID:26195794|gomodel:568b0f9600000294	IMP	MGI:1857199	F			gene	taxon:10090	20160119	GO_Noctua	negatively_regulates(GO:0006954),occurs_in(UBERON:0001155)

Should be:
MGI	MGI:96537	Il10	GO:0050728	PMID:26195794|gomodel:568b0f9600000294	IMP	MGI:1857199	F			gene	taxon:10090	20160119	GO_Noctua	occurs_in(UBERON:0001155)

Example #2 with an additional annotation:
MGI	MGI:99515	Syk Mmus		GO:0004713	PMID:26195794|gomodel:568b0f9600000294	IDA		F			gene	taxon:10090	20160119	GO_Noctua	occurs_in(CL:0011108),positively_regulates(GO:0007249)

Should be:
MGI	MGI:99515	Syk		GO:0004713	PMID:26195794|gomodel:568b0f9600000294	IDA		F			gene	taxon:10090	20160119	GO_Noctua	occurs_in(CL:0011108),positively_regulates(GO:0007249)

MGI	MGI:99515	Syk		GO:1903721	PMID:26195794|gomodel:568b0f9600000294	IGI	MGI:MGI:97312|MGI:MGI:99515   F			gene	taxon:10090	20160119	GO_Noctua	occurs_in(CL:0011108)

In the second case, we want to keep that original annotation because it is not to the root node and we want to add the annotation to the regulation term.
-D

**Comment by vanaukenk** [comment]
@ukemi 
If we go the route of adding relations to the relations/qualifiers column of the GAF, would we still need the folded annotations?

**Comment by ukemi** [comment]
We would still need them for traditional enrichment.

**Comment by ukemi** [comment]
Actually I realize now that I read this wrong, I was thinking of the annotation extensions. But I still think that for enrichment, we want to have the annotations to the folded terms available for users.
