### ISSUE TITLE
question about assigned_by in 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1760]
in this file
http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

some are assigned by  GOC and some by GOC-Owl
Why is that?

**Comment by kltm** [comment]
@ValWood Hm. Nothing rings a bell for me immediately here, but since the code has not changed in a long long time, it's unlikely to be something "new". Noting that it is currently 55 lines out of the total.
That said, looking at what's in the file, `GOC-OWL` only seems to appear when col16/extensions are populated. My guess would be that this was some mechanism to mark something as logically inferred in a different way and contrast them against the others.
@cmungall may have a recollection about this.
Examples from the end of the file
```
PomBase	SPNCRNA.1709	SPNCRNA.1709		GO:0031120	PMID:28432181	IC	GO:0030566	F	U2 snRNA-specific guide RNA		snRNA	taxon:4896	20170707	GOC-OWL	part_of(GO:0031120)	
PomBase	SPSNORNA.25	snoZ30		GO:1990438	PMID:11842100	IC	GO:0030563	F	C/D containing snoRNA Z30	mgU6-47	snoRNA	taxon:4896	20140807	GOC-OWL	has_input(PomBase:SPSNRNA.06),part_of(GO:1990438)	
```

**Comment by cmungall** [comment]
Yes, see
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000025.md

Creating more specific annotations by reasoning over extensions

**Comment by ValWood** [comment]
right, so is this the assigned_by for the method that unfolds and 
instantiates a BP  annotation that is in an extension?

v

**Comment by cmungall** [comment]
That's right. Technically not limited to BP, but this is where the majority
of cases can occur

E.g mitochondrial X activity, mitochondrial X component
