### ISSUE TITLE
Update metadata and make configuration changes for new filenames in June GOA release

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#190]
This replaces #185 

@tonysawfordebi has made the announcement

We need to:
- [x] modify go/software/utilities/filter-gene-association.pl - Mike
  - [x] propagate gaf, gaf_complex and gaf_rna (but not isoform) to the release directory
  - [ ] keep stale copies of old goa_foo and goa_foo_ref for a few months, and then retire
- [x] add JSON metadata files (these drive the main website) @kltm
- [ ] sync changes with legacy CVS repo (needs a CVS add)
- [ ] fix jenkins GAF validation/inference pipeline, we will only validate gaf for now - Mike
- [x] update amigo loader confs (e.g. [production](https://github.com/geneontology/amigo/blob/master/conf/examples/amigo.yaml.production) to include gaf, gaf_complex and gaf_rna @stuartmiyasato and @kltm 
- [ ] update config for legacy rdf-xml dump file in [Jenkins](https://build.berkeleybop.org/job/go-generate-pseudo-rdf-xml)
- [ ] communicate to community @cmungall

**Comment by hdietze** [comment]
First step in handling the renamed GAF files: the validation jenkins jobs have been updated to use the re-named goa files in the submission directory (updated Makefile and trigger filter for the jenkins job). 

There is no validation/inference for the `complex`, `isoform`, or `rna` additional files

**Comment by mcourtot** [comment]
Hi @cmungall @hdietze - where are the JSON files, and how does one go about updating them?

**Comment by monicacecilia** [comment]
Let's remember to make an announcement when these updates have been completed. Going by messages to the GOC Help Desk, the villagers are getting restless. :bowtie:

**Comment by kltm** [comment]
@jmcherry While updating the current metadata file in SVN in gene-associations/, I noticed that where the uniprot "noiea" file used to be, there is now a goa_uniprot_all_iea.gaf.gz? Is this correct, or should the pipeline be placing goa_uniprot_all_*no*iea.gaf.gz?

**Comment by kltm** [comment]
I've updated the go_annotation_metadata.json file to what I think it *should* be, but the "noiea" file is currently not there (see above).

**Comment by kltm** [comment]
As well, the SVN gene-associations/submission/Makefile target "goa_uniprot_noiea" would seem to be quite wrong now, both in target name and operations to no longer supported/extant files. I'd punt on this until the right files are checked in--easier to see what's going on.

**Comment by jmcherry** [comment]
sorry.  i just fixed it.  I deleted goa_uniprot_all_iea and added goa_uniprot_all_noiea


On Jun 23, 2016, at 2:01 PM, kltm <notifications@github.com<mailto:notifications@github.com>> wrote:


I've updated the go_annotation_metadata.json file to what I think it should be, but the "noiea" file is currently not there (see above).

**Comment by kltm** [comment]
@jmcherry Great, thank you. With that, I think I have all the metadata files in place again.

**Comment by tonysawfordebi** [comment]
I've just noticed that the goa_<species>_isoform GAFs are not available in http://www.geneontology.org/gene-associations, but they are in http://www.geneontology.org/gene-associations/submission - does a script/config file need to be updated somewhere?

**Comment by jmcherry** [comment]
A decision not to process the isoform files was made when GOA renamed its submitted files.  Thus the isoform files are not available from the main directory.  I'll defer to Chris to discuss the decision further.

-Mike

Sent from my iPad

On Jul 27, 2016, at 12:03 AM, Tony Sawford <notifications@github.com<mailto:notifications@github.com>> wrote:


I've just noticed that the goa__isoform GAFs are not available in http://www.geneontology.org/gene-associations, but they are in http://www.geneontology.org/gene-associations/submission - does a script/config file need to be updated somewhere?

-

**Comment by tonysawfordebi** [comment]
Really? By whom?

**Comment by cmungall** [comment]
The original assumption based on the README was that the isoform file 
corresponded to the non-GCRP entries in the old uniprot GAF. It was 
explicitly excluded on this basis, we require GCRP in col2.

However, it transpires that isoform is actually different, and is simply 
the set of annotations with c17 annotations. To be consistent with other 
GAFs we will merge these files together.

**Comment by cmungall** [comment]
@tonysawfordebi 
> Really? By whom?

By me, in this ticket. See the top of this ticket (Jun 18):

> propagate gaf, gaf_complex and gaf_rna (but not isoform) to the release directory

This was based on discussion in a previous ticket: #185 

See @valwood's comments. It seems we were all confused about the contents of the isoform file. Based on our new understanding, there is no reason to separate these. Am in discussion with @jmcherry about the best path forward. I think it's simplest if we have all the protein annotations in a single GAF, regardless of whether they have c17 filled in or not, so we're considering merging the two files in the submission dir to a single goa_X.gaf

**Comment by jmcherry** [comment]
Copying in a quote from an email between Chris and I below.

These goa_X files cound be merged on the server.  While possible I feel it would optimal for Tony to provide the one merged file rather than a script merging unfiltered files from the submission directory with the main filtered file.

-Mike



On 27 Jul 2016, at 10:07, J. Michael Cherry PhD wrote:


Chris correct me if I am wrong but should I merge two of the GOA files before processing or do you want GOA to do the merge?  Should I start processing the goa_isoform files?  Should I do nothing?

I would prefer GOA do the merge, but in the interests of moving forward, what is the easiest thing for us to do? If it's easy for you to do the merge (such that top-level goa_X = submission/goa_X + submission/goa_isoform_X), then go ahead and do this.




On Jul 27, 2016, at 2:46 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


@tonysawfordebi<https://github.com/tonysawfordebi>

Really? By whom?

By me, in this ticket. See the top of this ticket (Jun 18):

propagate gaf, gaf_complex and gaf_rna (but not isoform) to the release directory

This was based on discussion in a previous ticket: #185<https://github.com/geneontology/go-site/issues/185>

See @valwood<https://github.com/valwood>'s comments. It seems we were all confused about the contents of the isoform file. Based on our new understanding, there is no reason to separate these. Am in discussion with @jmcherry<https://github.com/jmcherry> about the best path forward. I think it's simplest if we have all the protein annotations in a single GAF, regardless of whether they have c17 filled in or not, so we're considering merging the two files in the submission dir to a single goa_X.gaf

**Comment by tonysawfordebi** [comment]
Not sure that I like the idea of the merged file, as that will mean that the sets of files available from the GOC and GOA sites will be different, which users will undoubtedly find confusing.

**Comment by cmungall** [comment]
I take your point. But it's also confusing if users have to download a separate file to get a complete list of protein-coding annotations for human, which they don't have to do for other organisms (the separation of RNAs and complexes makes more sense).

I don't really know what the use case is for downloading current goa_X file by itself.

The use case for the union of goa_X + goa_X_isoform is clear, this should be default. While not as complete as combing all, it can be used safely in a variety of contexts (e.g. should not bias basic enrichment results).

My choice would be to combine them and document the difference.

**Comment by tonysawfordebi** [comment]
*If* the files end up being combined, then the name of the combined file should also be changed to reflect this, and to mitigate against queries from users along the lines of "the version of goa_whatever.gaf that I downloaded from the GOC site is substantially different from the one I downloaded from the GOA site - why?"

**Comment by ValWood** [comment]
I'm not following this thread. Is this about the files  with isoform data beaing 'split -off' nto another file, I remember a discussion about this, at a consortium meeting. 

I thought the merge was to make GO/GOA consistent. Why will there be differences?

**Comment by pgaudet** [comment]
This work is now described in this ticket: 
https://github.com/geneontology/go-site/issues/2214

GOA is already producing the new files; GO central will load as soon as possible.
