### ISSUE TITLE
Clarify and create better documentation for orthologs GO_REF:0000096

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2019]
Seems quite out of date.
From conversation with @thomaspd @cmungall 
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000096.md

**Comment by ukemi** [comment]
WRT use of Alliance orthology instead of manually curated orthology as described.

**Comment by ukemi** [comment]
@pgaudet @sierra-moxon @LiNiMGI 

Since for the time being, we are using two different sources for orthology, I suggest we retain this GO-ref for the rat ISO annotations and create a new one for human. Modifications to this ref:

- title:Automated transfer of experimentally-verified manual GO annotation data to mouse-rat orthologs.
- author: The Gene Ontology Consortium
- external_accession: J:155856 and RGD:1624291???? (might want to revisit this one)
- id: GO_REF:0000096
- year: 2023
- layout: goref
- abstract: The Alliance of Genome Resources (https://www.alliancegenome.org/) has procedures in place to establish orthology relationships between genes. The experimentally-based annotations (IDA, IMP IPI, IGI, and EXP) annotated by Rat Genome Database (RGD) and The Mouse Genome Database (MGD) are used to provide annotations to the respective mouse and rat orthologs, and given the ISO evidence code and an entry in the inferred_from field to indicate the orthologous entity.

New ref (placeholder, still needs tweaking):
- title:Automated transfer of experimentally-verified manual GO annotation data to mouse-human orthologs.
- author: The Gene Ontology Consortium
- external_accession: J:164563 and RGD:1624291???? (might want to revisit this one)
- id: GO_REF:new
- year: 2023
- layout: goref
- abstract: Mouse Genome Database (MGD) has procedures in place to establish orthology relationships between mouse and human genes. The Experimentally based annotations annotated by each group (IDA, IMP IPI, IGI, and EXP) are used to provide annotations to the respective mouse and rat orthologs, and given the ISO evidence code and an entry in the inferred_from field to indicate the orthologous entity.

**Comment by pgaudet** [comment]
Hi @ukemi 

I creates a GOREF here: https://github.com/geneontology/go-site/pull/2213

We dont need to merge this if it's not ready. I think this is what remains to be done: 

- [ ] confirm the xref to RGD:1624291
- [ ] Update GO_REF:0000096 to be limited to rat (right?) 

I also wonder why the new GOREF mentions that the annotations are coming from Gene Ontology Annotation (GOA) Database? This is not a curation group.

Thanks, Pascale

**Comment by ukemi** [comment]
@pgaudet 
Thanks for taking a look at this. Who makes the annotation to human proteins? I thought it was GOA, but please change to the correct group.

**Comment by ukemi** [comment]
@pgaudet 
The modified abstract limits ref 96 to just rat-mouse orthology. So yes, but you should check with RGD to be sure that this in now ok with them. If I trace the GO reference to their web site, it looks like it contains a lot more.

@sierra-moxon @leemdi @LiNiMGI 
Once the new reference here goes live and the pipeline from the GOC is running, you should switch the human ISO pipeline to point to the new reference (GO_REF:0000119). @LiNiMGI we then need to have the new ref associated with J:164563 at MGI.

**Comment by pgaudet** [comment]
Many groups make human annotations, UniProt mainly, but I think most groups make human annotations; I thought MGI did too. Those would be propagated by the ISO pipeline, right? or is there a selection by source?

**Comment by ukemi** [comment]
I think in the abstract, we want to specify the source of the human annotations that we use to generate the ISOs. For rat, we use the RGD file.

**Comment by ukemi** [comment]
Maybe something like:
abstract: The Alliance of Genome Resources (https://www.alliancegenome.org/) has procedures in place to establish orthology relationships between genes. The experimentally-based annotations (IDA, IMP IPI, IGI, and EXP) for human genes provided by UniProt are used to provide annotations to the respective mouse orthologs, and given the ISO evidence code and an entry in the inferred_from field to indicate the orthologous entity.

**Comment by pgaudet** [comment]
Ah I see! How about 
"The experimentally-based annotations (IDA, IMP IPI, IGI, and EXP) for human genes **generated by the GOA pipeline** are used to provide annotations ..." ?

**Comment by ukemi** [comment]
That would work too.

**Comment by krchristie** [comment]
Considering that GO_REF:0000096 is currently written to be much broader than either of the specific human to mouse or rat to mouse ortholog determinations, I think it is a bad idea to rewrite this to be narrower. 

I think it would be better to leave GO_REF:0000096 as is and create two new GO_REFs for this need of MGI.

**Comment by pgaudet** [comment]
@krchristie 

Please go ahead and draft what the 2 GO_REFs should contain, and I will create them. 

Thanks, Pascale

**Comment by cindyJax** [comment]
One new GO ref (GO_REF:0000119) is already created but not yet merged. 
https://github.com/geneontology/go-site/pull/2213

GO_REF:0000096 is already revised but not yet merged. 

Please don't create more refs.

**Comment by kltm** [comment]
@pgaudet It looks like you committed code without a PR that breaks our tests: https://github.com/geneontology/go-site/commit/8a29ac3cfff75191cff08f653ea3d1eac3510621https://github.com/geneontology/go-site/actions/runs/7290843709/job/19868515113 . Please make PRs and check them when committing metadata and GORULES. #2213

**Comment by pgaudet** [comment]
Hi Seth, 

I am not sure exactly what I should do. 

I saw a 'passed QC' green box yesterday, so I merged. I dont know what is wrong.

**Comment by kltm** [comment]
@pgaudet No worries; we can talk Monday. I'll go ahead and try my best to fix in place so that tests can pass.

**Comment by sierra-moxon** [comment]
@kltm - is this good to go for me?  I can use 0000119 and 0000096 ?

**Comment by LiNiMGI** [comment]
it's working in the import file, thanks @pgaudet !

**Comment by kltm** [comment]
@LiNiMGI If this is done, can we move this to the "Done" state?

**Comment by LiNiMGI** [comment]
Since both GO_REF have been made and inserted into the pipeline, i think this one was done. Thanks, Li
