### ISSUE TITLE
Do not annotate terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2107]
Hello, 

Right now we have 2 types of do not annotate flags: 
do_not_annotate, with 135 terms
do_not_manually_annotate, with 72 terms

1) Do we need that distinction anymore? 
2) I would like to split these into the ones that are just reported ('soft checks'), and those that are filtered ('hard checks'). What I propose to do is to go through all the terms, and starting with those with fewest annotations, move them to the hard check list slowly.

How does that sound to everyone ? 

@vanaukenk maybe a topic for an annotation call ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't see the reason for this distinction, but I think it would be REALLY useful to have a distinction between

Do not annotate, this is a grouping term and it should be possible to make a more specific annotation
AND
Do not annotate, this term is pending obsoletion (because it represents a molecular function, is biologically incorrect  or is out of scope for GO)


This would be useful both for curators, and for those doing function prediction.

**Comment by pgaudet** [comment]
Done - we now have a single flag, giving a WARNING in GOC and a FILTER at GOA.
