### ISSUE TITLE
Automate MySQL dump loads for mirrors

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#213]
The previous system of loading MySQL dumps will no longer work.

The issue is that the previous scripted load that we did:

1. requires a level of database access that is not particularly safe
2. requires probing both the remote dump archive and local database timestamped db names to figure out if the most recent has been loaded and to skip

A safer and more effective system would be to simply load the latest load at a particular frequency and not worry about probing, locations, etc.

The simplest way forward would be to make the latest lite and seqdb loads available as non-dated downloads at a fixed location. We already do this for the daily termdb at http://archive.geneontology.org/ ; this would be an extension of that, but for slower builds. E.g.: go_monthly-seqdb-data.gz .

I know that we are looking to remove the MySQL sooner rather than later, but the current outage seems to have been rather disruptive to users and can be remedied  relatively easily. @stuartmiyasato @cmungall , any reason not to have this until we retire the dumps?

This is directly related to geneontology/amigo#375.

**Comment by stuartmiyasato** [comment]
@kltm I'm not really clear about the issue here.  Using the lite database builds as an example, is there an issue with users just going to http://archive.geneontology.org/lite/latest/?  I'm not sure why having the timestamp in the filename is an issue, so long as they are going to the correct directory.  Similarly for http://archive.geneontology.org/full/latest/.

Do you have an idea of how many users would actually benefit from this change?

**Comment by kltm** [comment]
As far as direct benefit, it would be me plus all the users of GOOSE, which turns out to be more numerous and vocal than expected. I assume others with pipelines would benefit, but with the eventual dropped of the mysql dump, probably not particularly long-term important.
The reason the dated files are a little hard to deal with is that there is no way of just downloading the latest via URL, as with all of our other resources, but rather the directory needs to be scanned and parsed to get the correct up-to-date file. Although, for some reason we have this for just the go_daily-termdb.
I having links at the top-level or undated links in /latest-* would be easy solutions around this. I'm trying to avoid having to re-write the old perl loader script that does indeed do the scanning, but needs full administrative access to the database (which it is no longer allowed to have) to do anything useful.

**Comment by stuartmiyasato** [comment]
@kltm I'm very hesitant to change our loading scripts (or more accurately, our pre-loading processing scripts) due to age.  The author of the key pre-loading script left our group probably close to a decade ago, and I don't really trust changing any old (and I mean OLD) perl code that still uses the &function_name syntax, IYKWM.  :)

> I having links at the top-level or undated links in /latest-* would be easy solutions around this.

This seems like a more reasonable solution, although I would have to dig in order to see where this would be inserted into the code and how likely I can do that without breaking anything.  I'm hoping there is some shell script where I can just drop in a few "/bin/ln -s" lines.  Let me take a look how hard this would be...

**Comment by kltm** [comment]
Cheers! The only thing on my want list is an unchanging URL for the latest full/lite dumps. Location and method are entirely flexible. Agree about trying not to touch old perl--I'm specifically trying to avoid changing my old, and maybe not quite as hoary, loader wrapper for the Jenkins loader.

**Comment by stuartmiyasato** [comment]
I probably did more digging than I really should have dedicated to this, but I think I found the one line that puts the datestamp into the filename.  I changed it, and if it is the correct place, we should see the results in this upcoming Saturday's weekly load.  The filename should be of the format go_weekly-assocdb-data.gz.  The resulting files should make it to the downloads server by roughly next week Wed. (8/31)  (Hopefully I didn't break this week's load by editing the script mid-load.)

**Comment by kltm** [comment]
Hey, no, awesome!
We don't have the GOOSE/MySQL pipeline chugging along yet, so a build fail won't really impact us yet. Will you have both dates and the generic, or are you switching it to just the generic?

**Comment by stuartmiyasato** [comment]
This would be just a wholesale switch to the generic filenames.  This assumes that my change doesn't affect the dates included in the parent directory's name.  Unfortunately I can't guarantee that -- it doesn't look like it will from what I've seen in the code, but it's been years since I last looked at it and I recall some rather surprising behavior, so I'm just going to look for odd behavior after the fact.

**Comment by kltm** [comment]
Fair enough. If poking around in there is a little weird though, it might be faster/safer to just write a little one-off that runs after the main job.
For example, getting the most recent file with something like (sorry, .json example):
```bash
 `find . -ctime -2 | grep "\.json$"`
```
and linking to that might be easier, and preserve the current naming scheme.

**Comment by stuartmiyasato** [comment]
@kltm It looks like the lite load finished with the desired change in the filenames.  Does

http://archive.geneontology.org/latest-termdb/

look correct to you?

**Comment by kltm** [comment]
That looks more or less right to me. Is the idea then to roll that out to the other types?

**Comment by stuartmiyasato** [comment]
@kltm Yes, the only remaining load type is the full load, and the code change has already been made for that one.  We should see the filename changes starting with the September full load when that completes.

**Comment by kltm** [comment]
Okay, I think this is all correct then. Once the lite and full percolate out, I can update the Jenkins job and can close this ticket.
Thank you for the in-production change!

**Comment by kltm** [comment]
Got a little excited to get this done and test--just dropped lite and am using the new jenkins job to reload it.

**Comment by kltm** [comment]
Good enough:
```
Jenkins build is back to normal : load-mirror-go-latest #506
```
Cloned job:
https://build.berkeleybop.org/view/GO/job/load-mirror-go-latest/
https://build.berkeleybop.org/view/GO/job/load-mirror-go-latest-lite
First (full) will run at 10pm on the first of every month.
Second (lite) will run Saturdays at 2am.
