### ISSUE TITLE
OBO in OWL files are inconsistent

### ISSUE THREAD

**Issue by cthoyt** [geneontology/go-site#2157]
Related to discussion at https://github.com/information-artifact-ontology/ontology-metadata/issues/157, there are three artifacts of the OBO in OWL ontology in this repo:

1. https://github.com/geneontology/go-ontology/blob/master/contrib/oboInOwl and https://github.com/geneontology/go-ontology/blob/master/contrib/oboInOwl.owl are OWL serializations
2. https://github.com/geneontology/go-ontology/blob/master/contrib/oboInOwl.obo is an OBO serialization

It appears that the OBO serialization is missing some key annotation properties, such as `SynonymTypeProperty`, which is available in the OWL serialization: https://github.com/geneontology/go-ontology/blob/master/contrib/oboInOwl#L474

How can we keep the OBO file up to date with the OWL one?

**Comment by cmungall** [comment]
Here is the history, but it's not very relevant. The oboInOwl vocabulary is encoded using an old version of the obo to owl mapping (https://www.bioontology.org/wiki/OboInOwl:Main_Page) that predated OWL2, and hence uses blank nodes and nested objects. This is suboptimal for multiple reasons, but it actually has zero impact as others have said here, the main use case for this vocabulary is as a source or URIs.

I wouldn't try and convert what is there to obo format using modern tools, that doesn't make sense since the owlapi uses a different mapping. I would just hand convert the owl to a normal owl2 representation. Then the obo conversion will make sense. This isn't a priority for any of us in GO but we would accept PRs

**Comment by pgaudet** [comment]
@cthoyt Do you want to convert the file? 

Otherwise we'll close without fix, as this is not a high priority for us. But thanks for pointing that out! 

Pascale

**Comment by cthoyt** [comment]
Unfortunately, as Chris mentioned, it's not possible to use modern tooling to update the OBO file from OWL (https://github.com/geneontology/go-ontology/pull/26371)

I'm disappointed that we can't come up with a first party solution for this, as it means that people who aren't insiders with knowledge of the history might not be able to easily interact with and understand the `oboInOwl` namespace.

Let's close this issue for now and when I get around to it, I will do my best to modernize the resources in the GO repo

**Comment by cmungall** [comment]
Hi Charlie, I'm not sure what you mean by "we can't come up with a first party solution for this", the correct solution is to make oboInOwl conform to modern oboInOwl - I'll see if I can find the time to do this, but not sure when, but the blocker is entirely resources/priorities
