### ISSUE TITLE
gorule-0000001  is incorrectly detecting test for gorule-0000061-17 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2219]
GORULE_TEST:0000061-17	is 

> ! FAILS GORULE:0000061 - TEST 17 - 'acts_upstream_of' is not allowed for a GO MF															
UniProtKB	A1B2F4	aztD	acts_upstream_of	GO:0004672	PMID:26468286	IDA		F	GORULE_TEST:0000061-17		protein	taxon:318586	20230427	GO_Central	

 'acts_upstream_of'  should be a valid relation, and therefore should not return an error for gorule-0000001; but in the 2023-12-19 run of the test GAF,  this is being picked up incorrectly by  gorule-0000001

**Comment by mugitty** [comment]
@pgaudet, The errors file has two entries for GORULE_TEST:0000061-17:

1. Line 229-230
! FAILS GORULE:0000061 - TEST 17 - 'acts_upstream_of' is not allowed for a GO MF															
UniProtKB	A1B2F4	aztD	acts_upstream_of	GO:0004672	PMID:26468286	IDA		F	GORULE_TEST:0000061-17		protein	taxon:318586	20230427	GO_Central	

2. Line 283-284
! FAILS GORULE:0000061 - TEST 44 - acts_upstream_of needs underscores										
UniProtKB	A1B2F4	aztD	acts upstream of	GO:0004672	PMID:26468286	IDA		F	GORULE_TEST:0000061-17		protein	taxon:318586	20230427	GO_Central	




The one on line 230 does not fail.  It gets a warning since annotations to MF terms are limited to {RO:0002327 "enables", RO:0002326 "contributes_to"}

        "gorule-0000061": [
            {
                "level": "WARNING",
                "line": "UniProtKB\tA1B2F4\taztD\tacts_upstream_of\tGO:0004672\tPMID:26468286\tIDA\t\tF\tGORULE_TEST:0000061-17\t\tprotein\ttaxon:318586\t20230427\tGO_Central\t\n",
                "type": "Violates GO Rule",
                "message": "GORULE:0000061: Found violation of: `Only certain gene product to term relations are allowed for a given GO term` but was repaired: RO:0002263 should be one of RO:0002327, RO:0002326. Repaired to RO:0002327",
                "obj": "",
                "taxon": "",
                "rule": 61
            }
        ],




The one on line 284 fails since qualifier is invalid
                {
                    "level": "ERROR",
                    "line": "UniProtKB\tA1B2F4\taztD\tacts upstream of\tGO:0004672\tPMID:26468286\tIDA\t\tF\tGORULE_TEST:0000061-17\t\tprotein\ttaxon:318586\t20230427\tGO_Central\t",
                    "message": "Invalid Qualifiers: acts upstream of",
                    "obj": "acts upstream of",
                    "rule": 1,
                    "taxon": "taxon:318586",
                    "type": "Invalid Qualifier"
                }


You can also verify from file assigned-by-GO_Central-report.html and do a search for GORULE_TEST:0000061-17

This is not a bug.  Please update the errors file and I will re-run.

Thanks

**Comment by pgaudet** [comment]
Hi @mugitty 

1. GORULE:0000061 - TEST 17 
> WARNING - Violates GO Rule:GORULE:0000061: Found violation of: `Only certain gene product to term relations are allowed for a given GO term` but was repaired: RO:0002263 should be one of RO:0002327, RO:0002326. Repaired to RO:0002327--`UniProtKB A1B2F4 aztD acts_upstream_of GO:0004672 PMID:26468286 IDA F GORULE_TEST:0000061-17 protein taxon:318586 20230427 GO_Central `
- this seems correctly handled by  GORULE:0000061  (repair), however why is it an ERROR in GORULE:0000001? 

2.  GORULE:0000061 - TEST 44 : I fixed the GO term, it's now a BP, so that may now be failing correctly.

**Comment by mugitty** [comment]
@pgaudet , GORULE:0000001 is failing due to invalid qualifier label: 'acts upstream of'

If qualifier label is fixed, then I can re-run
