### ISSUE TITLE
Confirm existence of GPI 2.0 file as output of pipeline, complimentary to GPAD 2.0

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2288]
The previous work in the MGI remainders project concentrated on the GPAD 2.0 output, which is what MGI will pick up--no need for the GPI as they are the SoT.

We want to make sure that we are actually producing a GPI 2.0 file to complement the GPAD 2.0 file we are producing.

As well, we would like to confirm what we want from our GPI 2.0 files; for example:

* pass-through upstream SoTs when possible
* produce best-effort when not

vs

* produce close compliment to our GPAD 2.0

**Comment by kltm** [comment]
In discussion with @cmungall, we may want to get out of the business of producing our own GPIs

* If there is a "proper" GPI upstream, we convert to 2.0 (if necessary) and make that available (light copy)
* If there is no GPI upstream, the choices are:
  * we produce an "in-house" GPI (i.e. GAF-derived like is done in NEO in some cases)

Easy to implement as: do what we do now, but clobber if we have a "proper" upstream (as found in the datasets.yaml).

**Comment by sierra-moxon** [comment]
update & Q's:  

in this branch (when it's merged), there are changes to move the _current_ process to produce GPI 2.0 so that we can now do the second option by default.  

To do the second option, in ontobo's validate.py, I would: 
  - parse each yaml file in go-site/metadata/datasets/ grab the GPI for the dataset group currently being processed, unzip, and read the GPI's header.
  - if the GPI is 2.0: parse it and dump it as is.
  - if the GPI is 1.2: parse it, convert it to 2.0, and dump it.
  - if there is no GPI listed in the yaml file, then generate it using the default behavior.

**Comment by kltm** [comment]
@sierra-moxon We can talk more on Thursday, but I think that, from your POV, for the scope of this project, we'd just keep doing what we've always been doing: produce the GPAD and GPI as you have in ontobio. Later on, as a separate step, something can go into the YAMLs and clobber stuff before it goes out the door. I think that we can "skip" the validation of the upstream GPIs for the moments, and leave the responsibility to the upstream.

**Comment by sierra-moxon** [comment]
ok, I will call it done then, in my ontobio branch.

**Comment by kltm** [comment]
In discussion, as a final step, we need to prosecute the YAML to copy forward the GPI forward.

Also brought up: mmmaybe we really should reconsider having GPAD as an external format. Maybe the products should just be GAF, with GPAD saved for "internal uses only" in a different location.

**Comment by kltm** [comment]
GPI confirmed as 2.0 in current pre-snapshot.
