### ISSUE TITLE
Jenkins GAF checks with red status cannot be inspected

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#267]
I'm not sure if this is a change in overall Jenkins config or if this has always been a problem

https://build.berkeleybop.org/view/GAF/

if we have yellow status (warnings) then the job is successful and we have a report that can be inspected by curators, e.g.:

https://build.berkeleybop.org/view/GAF/job/gaf-check-mgi/

however, if the status is red, then the last successful artefacts will not be for the most recent build as in here:
https://build.berkeleybop.org/view/GAF/job/gaf-check-fb/

Furthermore, the workspace is empty for fb and others with a red ball.

So once you get a red ball, it's impossible to inspect for errors locking you into a red state for ever, not good! The only option is for the submitter to run owltools checking locally, which requires installation etc

@ukemi - do you recall how this is meant to work? What do you do when you hit a red ball.

@kltm - any ideas?

**Comment by cmungall** [comment]
Hmm, here is a clue

MGI had a red ball in Sept:
https://build.berkeleybop.org/view/GAF/job/gaf-check-mgi/199/

Note that it shows the build artefacts, allowing the curator to check

However, for
https://build.berkeleybop.org/view/GAF/job/gaf-check-fb/48/

there are no build artefacts. 

So it looks like a deeper failure, caused by the ontology being in an incorrect state:
https://build.berkeleybop.org/view/GAF/job/gaf-check-fb/48/console

**Comment by hdrabkin** [comment]
I just looked: it seems that was due to a missing prefix, which we would have gone in and fixed.

**Comment by hattrill** [comment]
Chris: could you provide me with the commandline to check via owltools, I have failed to work it out myself!

**Comment by ukemi** [comment]
We just got a red ball on the most recent build/commit and you are correct, we cannot see any of the files to check for errors.

AFAIK we have never seen this before. The console output seems to indicate that there are still problems with the ontology. Here is a snippet:

2016-12-01 11:28:26,487 ERROR (GafCommandRunner:965) Unsatisfiable: UBERON:0005751 'visceral layer of glomerular capsule'
2016-12-01 11:28:26,487 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0051619 'inhibition of histamine uptake'
2016-12-01 11:28:26,487 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0051617 'negative regulation of histamine uptake'
2016-12-01 11:28:26,487 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0051618 'positive regulation of histamine uptake'
2016-12-01 11:28:26,487 ERROR (GafCommandRunner:965) Unsatisfiable: GO:0051615 'histamine uptake'

**Comment by hattrill** [comment]
Yes, problem seems to live beyond the gaf:

No validation report using owltools and http://purl.obolibrary.org/obo/go/extensions/go-gaf.owl) - log snippet:

------
2016-12-02 14:39:19,439 INFO  (GafCommandRunner:234) Finished loading GAF.
2016-12-02 14:39:26,395 ERROR (GafCommandRunner:961) Can't validate with an ontology with unsatisfiable classes
2016-12-02 14:39:26,943 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021582 'medulla oblongata maturation'
2016-12-02 14:39:26,943 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021583 'pons morphogenesis'
2016-12-02 14:39:26,943 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021580 'medulla oblongata formation'
2016-12-02 14:39:26,944 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021581 'medulla oblongata structural organization'
2016-12-02 14:39:26,944 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021586 'pons maturation'
2016-12-02 14:39:26,944 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021587 'cerebellum morphogenesis'
2016-12-02 14:39:26,945 ERROR (GafCommandRunner:964) Unsatisfiable: UBERON:0002437 'cerebral hemisphere white matter'
2016-12-02 14:39:26,945 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021584 'pons formation'
2016-12-02 14:39:26,945 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0044224 'juxtaparanode region of axon'
2016-12-02 14:39:26,946 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021585 'pons structural organization'
2016-12-02 14:39:26,946 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0044225 'apical pole of neuron'
2016-12-02 14:39:26,946 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021579 'medulla oblongata morphogenesis'
2016-12-02 14:39:26,947 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0021577 'hindbrain structural organization'
-----

Any other flavours of the GO and I get a validation report with the usual error I see with Jenkins:
# GO_AR:0000008	No annotations should be made to uninformative high level terms	Warning	count:	2
88821	GO_AR:0000008	Warning	Do not annotate to: GO:0000087 'mitotic M phase' The term is considered to high level, as marked via the subset tag: gocheck_do_not_annotate	FB	FBgn0003525	stg		GO:0000087	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR000751	P	string	0224/06|0245/03|0439/22|0730/13|0896/05|0967/05|0980/06|1083/13|1089/08|1143/02|5473|CDC25|CDC25[string]|CG1395|Cdc25|Cdc25[Stg]|Cdc25[String]|Cdc25[stg]|Cdc25[string]|Cdc25c|EP1213|S(rux)3A|STG|SY3-4|Stg|String|String/Cdc25|String/Cdc25 phosphatase|Suppressor of rux 3A|anon-EST:Liang-2.21|cdc25|cdc25/string|cdc25[string]|clone 2.21|l(3)01235|l(3)j10B9|l(3)j1D3|l(3)j1E3|l(3)j3D1|l(3)s2213|st|stg[cdc25]|str/cdc25|string/cdc25	protein	taxon:7227	20161112	FlyBase		
91727	GO_AR:0000008	Warning	Do not annotate to: GO:0000087 'mitotic M phase' The term is considered to high level, as marked via the subset tag: gocheck_do_not_annotate	FB	FBgn0002673	twe		GO:0000087	FB:FBrf0174215|GO_REF:0000002	IEA	InterPro:IPR000751	P	twine	BG:DS02740.1|CG4965|Cdc25|TWINE|Twe|Twine|cdc25|l(2)35Fh|mat(2)syn-A|mat(2)synHB5|mat(2)syn[HB5]|twn	protein	taxon:7227	20161112	FlyBase		

[Plus angry taxon complaints for every line - I assume that is because I didn't feed it a taxon file:
6	GO_AR:0000013	Warning	Could not retrieve a class for taxonCls: NCBITaxon:7227	FB	FBgn0043467	064Ya		GO:0048149	FB:FBrf0131396|PMID:11086999	IMP		P	064Ya		gene_product	taxon:7227	20060803	FlyBase		]

**Comment by ukemi** [comment]
Looks like this is spilling over to other things too. There was no inference file for us to pick up this morning because it looks like it is generated in the same job.

**Comment by cmungall** [comment]
Which job are you talking about?

**Comment by ukemi** [comment]
https://build.berkeleybop.org/view/GAF/job/gaf-check-mgi/
We pick up the inference file from the artifacts here. If you look at the older versions that did not red ball, you will see the gene_association.mgi.inf.gaf file.

**Comment by cmungall** [comment]
Ah yes, was aware of that but what was the ontology job - release-go?

**Comment by ukemi** [comment]
I just loaded the current editor's configuration into Protege and ran ELK. There are no unsatisfiable classes, so as far as our working version of the ontology and all of the imports, things all look fine. 

> So it looks like a deeper failure, caused by the ontology being in an incorrect state:
I don't think this is anything on the working version of the ontology's side. I think the errors must be due to a configuration of the checking script.

**Comment by cmungall** [comment]
Notes mostly for me and @kltm 

I see the gaf jobs all have

```
Post-build action:

"Delete workspace when build is done"
```

I removed this for the mgi, which preserves the workspace. However, this doesn't help much as the txt report file does't appear to be there

**Comment by cmungall** [comment]
> AFAIK we have never seen this before. The console output seems to indicate that there are still problems with the ontology.

OK, this is the root cause. The reasoner checks don't make sense until this is fixed.

We need a job that checks this import chain

**Comment by cmungall** [comment]
I made a job: https://build.berkeleybop.org/job/check-go-gaf

**Comment by kltm** [comment]
Okay, the issue is fairly simple: artifacts are not created and saved for unsuccessful jobs (as it is a post-build procedure) and workspaces are destroyed as they take entirely too much space (preventing inspection).

Now, how to get around this?

We cannot leave these workspaces around, so unless we start sharing them (a common workspace), we should archive somewhere else. What not push artifacts out sooner to our build S3? That's maybe where they belong anyways.

**Comment by kltm** [comment]
Talked to @cmungall -- nevermind!

**Comment by kltm** [comment]
@cmungall we'll need to revert that one job that didn't destroy its workspace when we were experimenting.

**Comment by pgaudet** [comment]
@cmungall @kltm 
I think these jobs are not active anymore - can we put a note and a link to the new, correct location of the reports ?

**Comment by kltm** [comment]
The newer documentation should be pointing to the new stuff. 
Also: https://github.com/geneontology/go-site/issues/702
