### ISSUE TITLE
GH pages?

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#284]
Looking at https://github.com/geneontology/go-site/blob/master/documentation/application-logins.md, wondering if it'd be worth creating GH pages (https://pages.github.com) as atm documentation is somewhat hidden.

**Comment by monicacecilia** [comment]
My initial reaction is 'not yet'.

I can tell that there is at least GOC documentation available on the GO wiki, on the GO website, and on the GO-GH repos. Some documentation is redundant from site to site and could be merged/deprecated as appropriate; other things are kept separated because some of it is internal to GOC members, some of it is meant for the outside world to consume for curation, and some of it is meant for software developers (and not necessarily worded with more biology-oriented scientists in mind).

I'm thinking that having GH pages would likely add yet another layer of complexity, possible redundancy, and possibly a few more nightmares. :bowtie:  But it may be an alternative the GOC leadership could to consider, say for the GO website in the future?

How about we first give the documentation overhaul a chance to make progress with just the three places we currently have, and we revisit as we clean up the current docs content? ... Does that make sense?

**Comment by kltm** [comment]
I'd chime in here, that at some level, the drupal site itself (not the docs/info), being a fairly expensive proposition, will likely be replaced with something along the lines of markdown/github docs. We're still looking at options, but it seems that we're heading towards something more minimal (and have less logins to deal with/remember).

**Comment by cmungall** [comment]
We're also adopting the obofoundry yaml-in-md metadata approach for rules and gorefs (see https://github.com/geneontology/go-site/tree/master/metadata), this is quite well suited to a gh-pages approach
