### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#310]
The objective is to eliminate redundancy:

- [x] Update stale / out of date content on website
- [x] Review FAQs: Develop FAQ categories and documentation, designate point person for each category of FAQ
- [x] Eliminate redundancy between GO website and GO wiki

**Comment by monicacecilia** [comment]
@thomaspd FYI, I rolled the card you wrote for the management project into this issue.

**Comment by monicacecilia** [comment]
@ukemi FYI this issue is listed in both [GO Management Project](https://github.com/orgs/geneontology/projects/1) and [GO Documentation Project](https://github.com/orgs/geneontology/projects/3) pages.

**Comment by kltm** [comment]
It's worth keeping in mind that as part of our roadmap we will be migrating away from Drupal, as part of the transition in a couple of months. This means that documentation moving forward will likely have different interconnects and items that are logically similar but on different pages will be joined. A lot of the details will be hammered out once we're closer.
Given that though, it's also worth keeping in mind that the look and feel of the site may greatly change with the next update, and that will affect how people want it displayed.

As well, from the third item in the list above (https://github.com/geneontology/go-site/issues/310#issue-204638496), assuming it means what I think it means, there should be *no* "syncing" of wiki and documentation--things need to exist in one place or another, not both. Synchronization issues were a huge problem for the updates we did a couple of years ago; let's not go down that path again. If you are unsure (this is a global "you") about where something should live, let one of us know.

Also, what is the best forum to register my skepticism about the second item in the list? I think what is needed here is a documentation/outreach person, rather than trying to further subdivide peoples' roles--subdividing has not been effective in the past.

**Comment by monicacecilia** [comment]
Thanks @kltm 
- I replaced 'sync' with 'eliminate redundancy'.  I'll eventually get to that chaos.
- As we discussed, I'll get started reviewing FAQ content (they are already categorized) with two goals in mind: improving quality of info for users searching through GO site, as well as further assisting GO Helpdesk rotation to address questions.

**Comment by kltm** [comment]
@pgaudet We'll have to work together on this as it is a necessary step in moving away from the current Drupal system.

**Comment by vanaukenk** [comment]
@kltm and @pgaudet 
For annotation-related documentation, I was operating under the assumption that all relevant documentation would be migrated to the go-annotation/docs repo and from there, published to one or more websites, e.g. geneontology.org or readthedocs
If that's consistent with what the folks at BBOP are thinking, then I'd just need some help with the initial steps of getting a new repo and files up and running on go-annotation.  @monicacecilia gave me a demo this week of how to go from github to readthedocs. 
If that's not the plan, then let's discuss next week in person.  Thx.

**Comment by pgaudet** [comment]
I think this is done.
