### ISSUE TITLE
Migrate shared annotation check script from old repo and reestablish

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#315]
Migrate the shared annotation check from the deprecated bbop-js repo (https://github.com/berkeleybop/bbop-js/tree/master/bin), fix it into node and the current libraries, and get it running under Jenkins again (http://build.berkeleybop.org/job/check-shared-annotations/).

**Comment by kltm** [comment]
@ValWood
I've ported what we used to have and set the job to run every day:
https://build.berkeleybop.org/job/check-shared-annotations/lastBuild/console
The Rules are now found at:
https://github.com/geneontology/go-site/blob/master/scripts/shared_annotation_check.rules

**Comment by cmungall** [comment]
Do we have this registered here? https://github.com/geneontology/go-site/tree/master/metadata/rules

**Comment by kltm** [comment]
Not that I know of. AFAIK, this never graduated from random experiment, and has never been any formal part of the pipeline.

**Comment by ValWood** [comment]
I have 2 (hopefully small) requests for the output.

1. could the  number of violations be a hyperlink  instead of:

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0006520%22&fq=isa_partof_closure:%22GO:0006310%22&sfq=document_category:%22bioentity%22

will make it easier to read.

2. Also could the GO term names be included. I have to look them up because even when I get through to AmiGO I only see the IDs used as filters.

**Comment by kltm** [comment]
Well, for 1, there is no way to create html-like links on the jenkins console (raw output), so I at least tried to make it not wrap the same way.

For 2, that requires an extra step and slow down the whole process, but obviously there should be an easy way to recover those names, so I've added that step, and tried to space out the output a little bit more.

**Comment by ValWood** [comment]
I can read that much more easily now, thanks!
