### ISSUE TITLE
Term Enrichment tool error with viewer for originating resource.

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#55]
When using the Term Enrichment tool at http://amigo.geneontology.org/rte

When entering a list of genes to analyze, if the user chooses the option "Originating Resource" from the "Results Viewer" menu, as seen in the first figure, a server error is reported. ("The server encountered an internal error and was unable to complete your request. Error message: Premature end of script headers: rte If you think this is a server error, please contact the webmaster."). 

![screen shot 2015-03-20 at 11 51 00 am](https://cloud.githubusercontent.com/assets/1714621/6791017/13a5b9c6-d169-11e4-85b5-a0d522f4d6a8.png)

![screen shot 2015-03-20 at 11 50 53 am](https://cloud.githubusercontent.com/assets/1714621/6791021/187c0428-d169-11e4-84da-e8bb990db500.png)

**Comment by kltm** [comment]
Huh. Something generally seems to be very wrong as I now no longer get a results page either, but rather a form that doesn't seem to work. I'm adding @mugitty for comment.

**Comment by kltm** [comment]
Also pinging on @cmungall, I'm still trying to figure out if this is upstream or not. There is at least some upstream component since I don't seems to be able to contact the server in some cases. As well, directly trying the URL:

http://pantherdb.org/webservices/go/overrep.jsp?ontology=biological_process&input=P31946%0AP62258%0AQ04917%0AP61981%0AP31947%0Abaxter%0AP27348%0AP63104%0AQ96QU6%0AQ8NCW5&species=HUMAN&correction=bonferroni&format=html

Takes me to a page with a submit button that is unresponsive, rather than results:

![panther-te](https://cloud.githubusercontent.com/assets/2687900/6791757/d5a4fbe0-d16e-11e4-877a-f09e5f91a2ca.png)

**Comment by kltm** [comment]
One consistent issue I seem to be able to reproduce is that the previous test URL always seems to go to an unresponsive form page:

http://pantherdb.org/webservices/go/overrep.jsp?ontology=biological_process&input=P31946%0AP62258%0AQ04917%0AP61981%0AP31947%0Abaxter%0AP27348%0AP63104%0AQ96QU6%0AQ8NCW5&species=HUMAN&correction=bonferroni&format=html

**Comment by kltm** [comment]
I believe the 500 error comes from production using a branch that doesn't have the fix from geneontology/amigo#171. I've added a fix to 2.1.x and will see if they can get that out.

I believe that this means that the only remaining issue is the (unresponsive) interstitial form.

**Comment by mugitty** [comment]
Unresponsive interstitial form has been fixed.

**Comment by monicacecilia** [comment]
Thank you @kltm :+1: 
@mugitty Until the 500 error has been cleared (visible until the change is pushed), I think this issue should remain as "Open". 
thanks for fixing the other form! :+1:

**Comment by kltm** [comment]
I've added unit tests to AmiGO to cover both labs and production TE situations. I'll tests in a bit to check the actual return data. 

Since the upstream issue has been cleared, any further problems are AmiGO's. I've reopened the relevant ticket there: geneontology/amigo#171

Production is currently looking to get a hotfix out (and then maybe clean it permanently with the release of 2.2.x).
