### ISSUE TITLE
Add pipeline docs on wiki

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#555]
curator-facing docs that explain the flow and where to go for reports

(also remember to update README in this repo, or remove)

**Comment by cmungall** [comment]
As a first pass, we have this figure as a high level consortium-centric overview:

https://docs.google.com/document/d/1uR_32I2PYwGl6wZcmENETBV1GsgVtDx_xiHv5fr4xWE/edit

@vanaukenk - should we aim to present this on the call in 2 weeks?

**Comment by kltm** [comment]
http://wiki.geneontology.org/index.php/Release_Pipeline

**Comment by hdrabkin** [comment]
I would think a time of the gaf pickup (date) that the report is from (assuming it's not taken from the SVN/gene-associations/submission folder anymore; 
I intend to put a link to the gaf check file into my Monday morning qc  links.

**Comment by ValWood** [comment]
So this is describing how the GO database is populated?
I guess this is sufficient detail, but I don't really know who  it is aimed at. @mah11  might be a better PomBase person to comment.

For reading so far:
So the database is only updated monthly? I thought AmiGO was updated weekly on Wednesday? Have I got that wrong?. It would be good to know when the updates occur and where we can find the dates, so that we can time our submissions appropriately (@mah11  may already do this, but this is the first I heard about monthly updates).

**Comment by ValWood** [comment]
This page needs a preamble at the top describing what the "release cycle" is generating?
(i.e release cycle for what?)

> It will then public the processes GAFs, GPADs, GPIs to S3, where it is available for the public to download
this sentence isn't clear?

Also "S3" is mentioned twice. I don't know what this is.

**Comment by kltm** [comment]
@ValWood Apologies, the documentation is going to be a little wonky over the next month as we work things out and transition the production site from Stanford to Berkeley. I've removed that odd S3 reference and tried to clarify that part a little more.
AmiGO releases are going to be functionally every month for a little while (working off of the monthly release), but we will look at stepping it up again off of the dailies once we are on firming footing.
