### ISSUE TITLE
Remove all defunct PAINT annotations with GO_REF:0000033 as reference

### ISSUE THREAD

**Issue by selewis** [geneontology/go-site#563]
These are archaic - left over from when that's the reference we used in 2014
Remove all of them, globally.

**Comment by kltm** [comment]
So the idea here would be to just have a straight-forward drop filter on anything with `GO_REF:0000033` anywhere in that field?

tagging @dougli1sqrd @cmungall

**Comment by selewis** [comment]
Yes, drop anything with GO_REF:0000033.

This may also be a slightly more subtle issue when there is a new build of the PANTHER trees because PAINT uses the PANTHER family number as the "reference". If a branch moves from one tree to another after a build then we'd be stuck in the same situation where these are treated as separate annotations when in fact they're the same thing. We'll need to address that too. 

But for now the big thing is getting rid of these truly ancient ones. (i.e. GO_REF:0000033)

**Comment by cmungall** [comment]
Why would this be done in the pipeline rather than at source in PANTHER?

**Comment by pgaudet** [comment]
This is strange - are none of them valid? Surely we haven't reannotated all
those families?

Le 13 mars 2018 8:39 PM, "Chris Mungall" <notifications@github.com> a
écrit :

**Comment by cmungall** [comment]
OK, I think I understand now. The source for all PAINT annotations are in PANTHER, and none of these use the generic GO_REF anymore. They all use PAINT_REF:nnnn, where nnn is the family ID.

However, we still have a number of stale or redundant PANTHER annotations swishing around in the system dating to before when we injected PAINT directly, and MODs uptook from PAINT years ago. We should get rid of these during the GOC import pipeline. Even if they are valid, they are redundant with what we get from PANTHER. We should also encourage MODs to get rid of these at source, since it's potentially confusing if a user compares the same gene on amigo and, say, wormbase.

For more details on the overall dataflow consult this diagram:
https://docs.google.com/document/d/1uR_32I2PYwGl6wZcmENETBV1GsgVtDx_xiHv5fr4xWE/edit

If this is correct this is what needs to happen:

 - [ ] we need to obsolete the GO_REF, as it's misleading: #564
 - [ ] @dougli1sqrd will need to filter these at GAF parse time. I don't know if it's worth documenting this as a rule or if we just go ahead and implement. I assume it's a short term need, based on:
 - [ ] coordinate with groups to remove these in their MODs or upstream database

**Comment by selewis** [comment]
@dougli1sqrd and @kltm - also delete all PAINT annotations circa 2014. These are clutter and wrong. Need only PAINT annotations from the most current set from Huaiyu. All others should be removed.

**Comment by kltm** [comment]
@selewis Can you give an exact formula for @dougli1sqrd to follow so we can add this to the gaf parser?

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/157

This will at least throw out GO_REF:0000033. I'll add a date filter once I hear more about that.

**Comment by cmungall** [comment]
This is now folded into #587
