### ISSUE TITLE
When merging GAFs, the source should take priority for fields such as gene symbol

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#591]
This would help with this:
https://github.com/geneontology/helpdesk/issues/112

Until this is fixed:
https://github.com/geneontology/go-site/issues/581

This applies to any field that is in a GAF but not GPAD (i.e fields that pertain to the gene and not the association). The source (ie pombase not paint) is the authority

**Comment by cmungall** [comment]
@dougli1sqrd and @dustine32 - maybe you can make a start on this tomorrow while you're waiting for the others to come in?

**Comment by dougli1sqrd** [comment]
@cmungall @ValWood Is there a place where we can query or dereference the object ID in column 2 to the associated gene product symbol, in column 3? In this way we can detect that the contents of a column 3 gaf is correct, given what the database source expects. It's our understanding that the PAINT situation outlined in the helpdesk ticket is wrong because `SPAC1A6.10` can be dereferenced to the symbol `tcd1`, but in the PAINT gaf they have `SPAC1A6.10`.

**Comment by cmungall** [comment]
I spoke to Eric and Dustin and explained the issue and that the PomBase files are authoritative

**Comment by ValWood** [comment]
Any progress ensuring these don't get into Amigo until validated by Pombase?

**Comment by kltm** [comment]
@dougli1sqrd @dustine32 @cmungall Any word on progress here?

**Comment by dustine32** [comment]
Sorry about the lateness! @huaiyumi wrote a script to update the paint pombase GAFs using PomBase's [all_names.tsv](ftp://ftp.pombase.org/pombe/names_and_identifiers/allNames.tsv) gene symbol file.

It's pretty straight-forward: For each GAF line check the line's PomBase ID against this lookup table and replace if incorrect. @ValWood @cmungall I assume if the line's ID is missing a corresponding symbol in this lookup, it means column 3 should equal the PomBase ID in column 2? There are 47 instances of a line's column 3 containing a symbol but not having a symbol in the lookup. Ex:
```
PomBase	SPAC1B3.08	csn12		GO:0070390	PAINT_REF:12732	IBA	PANTHER:PTN000296424|FB:FBgn0036184|SGD:S000005433	C	Protein CSN12 homolog	UniProtKB:O13873|PTN000296481	protein	taxon:284812	20180402	GO_Central
```

I couldn't even find a "csn12" gene existing in PomBase, so column 3 should be changed to "SPAC1B3.08".

**Comment by dustine32** [comment]
And it also looks like column 10 DB object name is off. I can use the sysID2product.tsv mapping to fix these. So for the example above, "Protein CSN12 homolog" would change to "TREX2 comlex subunit (predicted)".

**Comment by cmungall** [comment]
@dustine32, I don't know about the all_names.tsv file. Not sure why you need this when we already have the source pombase file, which is authoritative. However, if it gives the same results this is fine (although I worry about the complexity of the overall dataflow by adding more files).

The metadata about where the authoritative file lives is always in [go-site/metadata/datasets](https://github.com/geneontology/go-site/tree/master/metadata/datasets). Here is [pombase.yaml](https://github.com/geneontology/go-site/blob/master/metadata/datasets/pombase.yaml). 

this is what pombase provides in c3,10 for SPAC1B3.08

```
$ curl -s -L  http://geneontology.org/gene-associations/submission/gene_association.pombase.gz | gzip -dc | grep SPAC1B3.08 | cut -f3,10
SPAC1B3.08      TREX2 comlex subunit (predicted)
SPAC1B3.08      TREX2 comlex subunit (predicted)
SPAC1B3.08      TREX2 comlex subunit (predicted)
SPAC1B3.08      TREX2 comlex subunit (predicted)
SPAC1B3.08      TREX2 comlex subunit (predicted)
```

so the column 3 and 10 of what paint produces must match this.

(aside to @ValWood: I'm not sure why your submitted GAF doesn't use a symbol here, [on your site](https://www.pombase.org/gene/SPAC1B3.08) it is "TREX2 comlex subunit (predicted)")


the subject of the original helpdesk ticket:

```
$ curl -s -L  http://geneontology.org/gene-associations/submission/gene_association.pombase.gz | gzip -dc | grep SPAC1A6.10 | cut -f3,10
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
tcd1    tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)
```

as long as the PAINT output matches this we are good

**Comment by dustine32** [comment]
@cmungall The all_names.tsv was more for use upstream on @huaiyumi 's end to fix the paint_pombase GAFs _before_ they go through the pipeline, like for a short-term one-off (or two-off?) run to fix the broken GAF file. I guess I could use the current PomBase GAFs but I figured this all_names would be similar to a GPI file.
Apologies, I realize this probably wasn't the right ticket to ask my question in since #591 is more about changing the GAF merge process in the pipeline.

**Comment by cmungall** [comment]
> The all_names.tsv was more for use upstream on @huaiyumi 's end to fix the paint_pombase GAFs before they go through the pipeline, like for a short-term one-off (or two-off?) run to fix the broken GAF file.

Yep, got it, but I still worry about the complexity of the overall dataflow rather than the strictly GO-central part. I'm imagining a scenario a few years from now where this short-term one-off becomes a permanent solution, pombase change their formats, then we're back to complex dataflow debugging...

But I'm just a worrier, go ahead and implement if it works on your end

**Comment by ValWood** [comment]
I'm a bit confused.

1. csn12 where does this come from ? it isn't in our files?
ftp://ftp.pombase.org/pombe/names_and_identifiers/allNames.tsv

but Chris is correct, all of the names are also in the appropriate fields in of GAF submission.
(I supply  this file to UniProt because it is used by them to align their names with ours,  and for the proteome datasets for  quest for ortholog, but GO should not require it.

2. I'm still a bit confused why this is required.  PomBase is authoritative for  gene names AND for annotations. Therefore  if the GO do not include the PAINT annotations until we have approved them, all of the problems will go away. Once we validate the PAINT files we will make sure that they come to GO with all of the correct names? PAINT only needs to use the systematic IDs in this case. The problems only arise because they are included in GO and have not come via PomBase
https://github.com/geneontology/helpdesk/issues/112
If we could default to this it would be fine  (I  think PomBase are the only ones not importing PAINT because we are quite fussy about annotation issues (we  always fix or filter known errors immediately so it would be odd to import a file which  has so many known anomolies).

3. 
> this is what pombase provides in c3,10 for SPAC1B3.08

> (aside to @ValWood: I'm not sure why your submitted GAF doesn't use a symbol here, on your site it is "TREX2 comlex subunit (predicted)")

our GAF has:
PomBase	SPAC1A6.10	tcd1		GO:0005524	GO_REF:0000037	IEA	UniProtKB-KW:KW-0067	F	tRNA threonylcarbamoyladenosine dehydratase Tcd1 (predicted)

http://www.geneontology.org/page/go-annotation-file-format-20
2 | DB Object ID | required | 1 | P12345
3 | DB Object Symbol | required | 1 | PHO3
10 | DB Object Name | optional | 0 or 1 | Toll-like receptor 4


so its
2 SPAC1A6.10
3 tcd1	
10 threonylcarbamoyladenosine dehydratase Tcd1

2 SPAC1B3.08
3 SPAC1B3.08
10 TREX2 comlex subunit (predicted)

?

**Comment by ValWood** [comment]
Oh I see what you mean.   "TREX2 comlex subunit " is the DB object name (which is essentially a gene product description label) but it does not have an official symbol yet. fixing that typo now too!

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/171
