### ISSUE TITLE
Implement taxon checks in pipeline against PAINT data

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#758]
The idea is to have the ontology taxon constraints active during the pipeline; report or report/filter is TBD (tagging @selewis and @cmungall for discussion).

@dougli1sqrd Is there a related GO Rule already? Maybe we should merge these tickets.

Seeded from: https://github.com/geneontology/go-annotation/issues/1873

**Comment by pgaudet** [comment]
The rule exists as a report

However I am not sure it's correctly implemented: some terms trigger errors that should not (see https://github.com/geneontology/go-site/issues/734) 

For the rgd file, 
* In the 2018-07-03 release there are > 6,000 errors (http://release.geneontology.org/2018-07-02/reports/rgd-report.html)
* In the snapshot (date unknown) there are no errors (http://snapshot.geneontology.org/reports/rgd-report.html)
* I cannot find any GO_AR:0000013  (the rule number for the taxon checks) in the snapshot files. 

1. We need an explanation for the discrepancy 
2. We need to implement the rule as a FILTER, not a REPORT. 


Thanks, Pascale

**Comment by kltm** [comment]
@dustine32 We were wondering if you might have some bandwidth to help us out with this?
The idea would be to have this implemented as an (efficient) by-line check during the GAF parsing phase.

**Comment by dustine32** [comment]
@kltm I can probably be of some help. I've taken a quick look at the GORULEs implementation in ontobio (cuz of the IBA filtering in GAF parser). Is this where you guys are thinking to put the check?

I forgot again exactly where the taxon constraints currently live. In the ontology files? I believe @thomaspd has some manually-curated taxon constraints also needing to be incorporated.

**Comment by mugitty** [comment]
Although the PAINT software does not enforce the taxon constraint rules.  I need a taxon constraint lookup file to warn the curators when annotations fail the constraint rules.

**Comment by kltm** [comment]
@dustine32 Yes, the idea would be to have the filters as described above incorporated into the ontobio for filtering at parse-time.
Tripping would output the GO Rule violation reference as well as a short explanation.
The constraints themselves are in the ontology files.
If there are other constraints to me made, they should be formally described in a/the rule, etc., etc.

**Comment by dougli1sqrd** [comment]
@dustine32 we can work together on this if you want, if you have the time. Yeah, the qc check would go in the qc.py file in ontobio (if possible).

**Comment by pgaudet** [comment]
@selewis 

> The only adjustment was for taxon violations found in EXP annotations would not be filtered out, they would only be reported as a warning.

We want all violations to be filtered. The reports should let people know what they need to fix (and here the snapshots will be very helpful, to correct errors between releases). 

Pascale

**Comment by cmungall** [comment]
We need to be conservative in filtering. A single mis-placed relationship in the GO ontology or any imported ontology could accidentally cause 1000s of valid annotations to be removed. This is because the constraints propagate over certain chains of relationship types. I have been debugging taxon errors in multiple ontologies for years, issues can be nuanced. This is compounded by the fact that GO is often fuzzy about the interpretation of many anatomical terms, see the recent discussion in excretory systems.

**Comment by pgaudet** [comment]
@cmungall I'd like to see what you are looking at. When I look at reports all the taxon failures seem to report a real pb (note that for several days there are no more reports of taxon problems, looks like the query is broken). 

Pascale

**Comment by dustine32** [comment]
Thanks @dougli1sqrd ! I'll try to get an idea of an approach and then maybe bring it up tomorrow on the dev call. Is there a ticket in ontobio I can use to name a branch?

**Comment by dougli1sqrd** [comment]
@dustine32 there are three currently open go-site taxon check tickets in the pipeline project. I'm not sure which is best to use.

**Comment by kltm** [comment]
You can use this one for coordinating the GO side of things, and a TBD ontobio one for that side.

**Comment by dougli1sqrd** [comment]
I created https://github.com/biolink/ontobio/issues/218

**Comment by dustine32** [comment]
Awesome, thanks @dougli1sqrd !

**Comment by cmungall** [comment]
@pgaudet: 

> * In the 2018-07-03 release there are > 6,000 errors (http://release.geneontology.org/2018-07-02/reports/rgd-report.html)
> * In the snapshot (date unknown) there are no errors (http://snapshot.geneontology.org/reports/rgd-report.html)

I looked at the first reported problem:

GO_AR:0000013	Taxon-appropriate annotation check	Warning	count:	6297
381312	GO_AR:0000013	Warning	Could not retrieve a class for taxonCls: NCBITaxon:	UniProtKB	A0A0G2K2M5	GO:0005829	PMID:21873635	IBA PANTHER:PTN001624706|UniProtKB:Q99865|UniProtKB:Q9BPZ2|UniProtKB:Q9Y657	C	Uncharacterized protein	UniProtKB:A0A0G2K2M5|PTN002234552	protein	NCBITaxon:	20180118 GO_Central	

This is clearly bad reporting from owltools. This is not a taxon violation. OWLTools is reporting that it does not know anything about the taxon with ID `NCBITaxon:`. This was because it was fed a GAF with a taxon field with just `taxon:` and no number. This was all described in another ticket.

This was all fixed in the upstream source (PAINT), hence the discrepancy

Apologies that the owltools reporting is so confusing. This will be fixed by the better reporting @dougli1sqrd is doing.

**Comment by pgaudet** [comment]
@dougli1sqrd says that the ontobio check for missing taxon happens before the owltool check, and in these cases the offending lines should be filtered and that error should never be reported like this anymore.
