### ISSUE TITLE
Add species filter for shared annotation checks (gorule-0000009)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#867]
To make this  easy for groups to check their intersections, could we have a species filter on the shared annotation checks.

http://snapshot.geneontology.org/reports/shared-annotation-check.html

**Comment by RLovering** [comment]
also it is confusing to have the gp count column. The 'number' link to an amigo view of the annotations lists the 'source'  rather than the 'contributor'. So for the UCL team using the gp count URL it looks like we have no edits because the annotation lists by source. whereas using the 'annotation link' for the same 'query' row provides the 'contributor' information in each annotation, so I can see UCL annotations.
Thanks
Ruth

**Comment by cmungall** [comment]
Closing as dupe: https://github.com/geneontology/shared-annotation-check/issues/2
