### ISSUE TITLE
gorule-0000006: implement in ontobio

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#875]
GORULE 6 used to use a sparql implementation, but it is too slow. So since we removed it, we should add an ontobio implementation.

**Comment by dougli1sqrd** [comment]
Currently no reports of gorule 6 violations, indicating that it's cleared.

**Comment by pgaudet** [comment]
@dougli1sqrd I am not sure what you mean. 

1. gorule-0000006 is not listed with the other ontobio rules: http://snapshot.geneontology.org/reports/gorule-report.html
will be there at the next snapshot release? (otherwise maybe you closed this too soon?)

2. There are annotations that fail this rule: 
In AmiGO, there are 57  MF and 29 CC. 

Can you please explain what you did on this ticket? 


Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Oh I just discovered what happened. Sorry, you're right. I have to do one more thing to link up the rule into the ontobio system.

**Comment by pgaudet** [comment]
ok, thanks for checking. 

Please don't close tickets until we see that the implementation is OK. 

Thanks, Pascale

**Comment by pgaudet** [comment]
OK, in the list of rules returning errors on snapshot
http://snapshot.geneontology.org/reports/gorule-report.html
