### ISSUE TITLE
Some rules should not show up in general reports

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#884]
Since this is just excluding the PAINT annotations that are submitted by groups.

**Comment by kltm** [comment]
This issue has two parts. This first part is to add a field, such as `silent` to the rules schema to indicate that it is not of general interest for internal QC/QA. The second part is to implement this so that the default interface for the reports does not display such rules violations.

As a starting case, add this feature to hide (or remove) rule 0000026 from the general reports.

**Comment by pgaudet** [comment]
Great! @kltm if you want to add this new field to gorule-0000026 as an example, I can then add it to all others. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
This would be under filter, report, etc? Or a new field entirely in the spec?

**Comment by selewis** [comment]
Let's chat please and get this sorted.

**Comment by kltm** [comment]
After discussion with @selewis and @dougli1sqrd , it would be a TBD list field that tags rule violations in the global violation capture, allowing different report interfaces to be filtered as necessary into the violation subsets of interest.

**Comment by dougli1sqrd** [comment]
To expand mildly from a discussion with Seth (@kltm): this work for this ticket will involve adding a tag of `silent` to any gorule we do not want to appear in the ontobio main reports (http://snapshot.geneontology.org/reports/aspgd.report.md which exists inside aspgd-report.html). Ontobio will add just add an additional field to each message containing tags from each rule message. So for example, when rule 26 is triggered, we will add the `silent` tag as a field to the message. 

When ontobio later generates the markdown file from all the different report messages, it will not include messages with the `silent` tag marked. Ontobio will not just *know* to do this, we will have some kind of configuration (whether from a command line, or otherwise) that will server as a controller for what to do on `silent`. This is the easiest path forward for this particular ticket.

@kltm and I both agree a reporting overhaul is due in ontobio, a ticket is soon to come to represent that future, larger work.

**Comment by pgaudet** [comment]
I dont think the 'silent' tag is in the schema. How is this implemented ?

**Comment by dougli1sqrd** [comment]
This is complete, and rule 26 is being silenced.

**Comment by pgaudet** [comment]
Can you please update the schema so we know where to put the 'silent' information?
https://github.com/geneontology/go-site/blob/master/metadata/rules.schema.yaml

I think this is in 'tags' - @cmungall has mentionned this should be an 'enum' value rather than a string. 

@dougli1sqrd Can you do the necessary changes ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Yes, `silent` is a tag. Rule 26 is an example of the current usage. This is picked up by the pipeline and currently Rule 26 is not reported in the reports page or in the main dataset report page. 

But I can also switch the schema here to specify the only existing tag as `silent`.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1163
