### ISSUE TITLE
Implement gorule-0000005 IEA, ISS, ISO, ISM, ISA, IBA, RCA annotations ae not allowed for direct annotations to to 'protein binding ; GO:0005515 or   GO:0005488 binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#887]
Need to first check with curators /QC group. 

@vanaukenk @ValWood @sylvainpoux @selewis

**Comment by ValWood** [comment]
I  think I have made ISO annotations to protein binding when I am very confident and I don't have pombe data. I didn't know this was disallowed...

**Comment by pgaudet** [comment]
Well it has only been proposed, never been implemented )(neither in P2GO, as far as I know). 

The issue is that the format doesn't allow us to specify both with and from (right?) - but really I think the solution should be fixing the format - these annotations may be useful if we can keep the 'with' information.

**Comment by ValWood** [comment]
It turns out we don't have any manual ones, but  there are a lot of IBA. I would vote for no IBA, ISS, ISM for sure.

I might be tempted to allow ISO if there was a piece of information that you really wanted to capture, but i don't  have an example.

Of course i would expect to be able to ISO to any protein binding children

like protein binding,bridging
protein membrane anchor etc.

**Comment by ValWood** [comment]
> The issue is that the format doesn't allow us to specify both with and from (right?) 

yes that is probably why I never did it!

**Comment by ValWood** [comment]
related, I notice that there are lots of ISM to 

function binding
i.e. 
kinase binding

I would prefer that we did not make these annotations. We will filter these at PomBase because they are confusing to our users, and they are not consistently annotated. We don't want users (community curators)  to request a binding term for every function. It is also unsustainable. Pombe  has over 100 kinases. We already have  100's of binding partners for some of  these. 

When we know binding partners we capture with protein binding and the specific gene product, or as a substrate (as we do for everything else). There are probably  thousands of  known "protein kinase binding" for fission yeast.   Only 22 are annotated (all by IBA). We could never do this consistently so we should not  curate at all.....

**Comment by kltm** [comment]
After discussion, this needs more work and organization from outside parties. We will revisit later on.
@pgaudet @dougli1sqrd @kltm

**Comment by pgaudet** [comment]
Discussion with @ukemi @vanaukenk 

Could be allowed if we use 'has_input' for the bound entity. The entity from that species should be from the same species as the annotation (Col 2). 

The with/from would be the original annotated entity.

**Comment by pgaudet** [comment]
1. ISS annotations to GO:0005515 protein binding: 
* with/from must refer to an annotation with the IPI evidence code
* has_input is mandatory should be a gene from the species being annotated

2. ISS annotations to **a child of** GO:0005515 protein binding: 
2.1 If the original annotation has the IPI evidence code: 
* with/from must refer to an annotation with the IPI evidence code
* has_input is mandatory and should be a gene from the species being annotated

2.2 If the original annotation has the IDA evidence code: 
-> The 'has_input' field should be null

**Comment by pgaudet** [comment]
This is no a line-by-line check so it will not be implemented right away.

**Comment by pgaudet** [comment]
Need to confirm with annotation group that we want to implement this check.

**Comment by pgaudet** [comment]
Changed status to 'implemented', see https://github.com/geneontology/go-site/pull/2318

**Comment by pgaudet** [comment]
Seems OK on snapshot. 

I still need to check whether this is OK in the tests from the test GAF. 

@mugitty will send an updated version of the file.

**Comment by pgaudet** [comment]
3 tests are failing correctly. 
Correctly showing up as warnings in snapshot.
