### ISSUE TITLE
Add "Qualifier is valid" to gorule-0000001

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#901]
P2GO rule
I think this is checked as part of Rule 1; @kltm should we make a separate rule ?

**Comment by dougli1sqrd** [comment]
We currently tag incorrect aspect as rule 28, "Aspect can only be one of C, P, F and should be repaired using the GO term"

**Comment by pgaudet** [comment]
@dougli1sqrd The qualifier is 'NOT', contributes_to' and 'colocalizes with'.  I dont understand how your comment is related to the proposed rule?

**Comment by kltm** [comment]
This can be closed when there is a rule and implementation so that a line-by-line check for column 4 to be in the set of 'NOT', contributes_to' and 'colocalizes' or empty (or combo). See GAF documentation.

This is likely a "solid" gorule-0000001.

This is also likely to be easily implemented and just needs prioritization.

So say we all: @pgaudet @dougli1sqrd @kltm

**Comment by dougli1sqrd** [comment]
This is fixed here: 
https://github.com/biolink/ontobio/blob/master/ontobio/io/gafparser.py#L523

Bad qualifiers will cause the line to be thrown out with an gorule-0000001 error.

**Comment by pgaudet** [comment]
Thanks !
