### ISSUE TITLE
Use synonym metadata to upgrade GAF sources (still a lot of  odd "source databases")

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#950]
![purge](https://user-images.githubusercontent.com/7359272/49442917-cf64b580-f7c2-11e8-8d14-b85add7a3fbc.jpg)

Should't these be hard checks ?

**Comment by ValWood** [comment]
refereing to 
AGBASE
FLYBASE
GO_CENTRAL
WormBase

@pgaudet

**Comment by pgaudet** [comment]
@dougli1sqrd Can you tell what is the source of these ? 

Also, shouldn't they get repaired ?

**Comment by cmungall** [comment]
To clarify:

A subset of these (FLYBASE, GO_CENTRAL) do not use the correct case, and should be repaired (which rule is this?)

Some of these refer to defunct annotation groups. We should track these down, ensure we have an entry in groups.yaml for every one of these. I don't think @dougli1sqrd should do this, best done by someone with historic knowledge of the GO. But if you want a specific report Eric can help with this.

Note we are already doing this for some, e.g. ASAP #949

**Comment by dougli1sqrd** [comment]
@pgaudet So `assigned_by` is not repaired. All we have is the groups.yaml: https://github.com/geneontology/go-site/blob/master/metadata/groups.yaml. This only provides the list of allowed groups, and gives no mappings from bad groups into correct groups (otherwise we could repair). As such, this is only a report rule, and does not filter. So that's why you're seeing them in the data still. They'll show up under rule 27 though in the report page. Before the `assigned_by` check went in, I  added at least a dozen unrepresented groups into the groups.yaml.

**Comment by selewis** [comment]
@dougli1sqrd - exactly Eric. I was going to add the code to repair these. There is absolutely no reason not to just go ahead and fix them where we can.

**Comment by dougli1sqrd** [comment]
Hi @selewis, if we're adding code to repair these, we need to know the mapping of {bad id} --> {good id}. Ontobio already uses the go-site groups.yaml (linked above) to test if `assigned_by` is present in the groups. Let's a an optional key to the groups.yaml called `synonyms` that represent values that are inappropriate, but that we can repair to the correct value (represented by the `shorthand` key). `synonyms` would be a yaml list. I can add this to the schema. 

The motivation here is that we don't want to encode mappings of bad --> good ids directly in the python code. As much of this should be controlled by metadata. These mappings shouldn't duplicated in any other code for GO. groups.yaml is already taken in by ontobio and is used to detect assigned_by violations. If we want to upgrade, that is a natural place to add that mapping information.

**Comment by dougli1sqrd** [comment]
One danger though is we'll have to make sure that no synonym for any entry is the same as any other synonym, since we wouldn't be able to correctly resolve the repair. Like, if we have bad1 --> good1, and also bad1 --> good2, we wouldn't be able to choose, so we can't share any synonyms across group entries.

**Comment by selewis** [comment]
@dougli1sqrd yes that's exactly the approach to take, nothing hard-coded. 

by coding I merely meant that something needs to be there to check for these synonyms if the assign_by tag is wonky. to my knowledge that checking piece isn't there.

it's more likely many bads to one good. I can't think of any cases where it's the other way around

**Comment by pgaudet** [comment]
Can we just fix the case ? Any other problems should not be repaired IMO. 

Pascale

**Comment by selewis** [comment]
It's not just case (e.g. WormBase or WB), but it's not any more difficult. All are easy

**Comment by selewis** [comment]
@pgaudet - also, if it is something quite weird (e.g. boogalooDB) then they won't be repaired but will be reported as errors.

**Comment by pgaudet** [comment]
But we should never have WB. And there are few! We need to locate where these are coming from and get them fixed 'upstream'.

**Comment by selewis** [comment]
No worries either way. If the name is not the primary one then all the synonyms will be checked. If a matching synonym is found then the primary name will replace the synonym and the repair will be reported. Else if there is no synonym found then the line will be removed and the error will be reported. It all comes down to which names do we want repaired (i.e. add synonym to the yaml).

**Comment by ukemi** [comment]
Always preferable to correct data at its source.

**Comment by dougli1sqrd** [comment]
Do we want to remove lines that do not have a repairable synonym? Or keep them as a warning as we currently do?

**Comment by selewis** [comment]
We don't want to load data into the public resource if we don't know where it came from. It would be unsound to have such data incorporated . 

But these lines don't disappear, they'll be available intact within the report itself so that they can be tracked down and fixed upstream at the source. (if we can figure out what it is)

For those that are repairable, the obvious ones, these will appear as warnings within the report for fixing, but the lines won't be removed so these at least get into the public store.

 If this isn't clear enough let's talk tomorrow.

**Comment by dougli1sqrd** [comment]
@cmungall You don't think we should add a synonyms mapping and repair from synonyms?
