### ISSUE TITLE
GO Rules: Add example passing/failing data to go rules

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#968]
Now that we have a yaml schema in place for the go rules to add example passing and failing data (https://github.com/geneontology/go-site/issues/956) we can add the data to the go rules. This data can be read by software to perform the comparison test.

**Comment by dougli1sqrd** [comment]
@pgaudet has created many examples already here: https://drive.google.com/drive/folders/12H6Kz9BsFEhtllx7CMy9OW29FeiC8GwQ

**Comment by pgaudet** [comment]
File is here https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf

**Comment by kltm** [comment]
@pgaudet @mugitty What test suite is this part of? The file should be in `/tests/`, not user documentation. If the test suite is not in go-site, that will complicate testing and this should probably be in the appropriate repository.

**Comment by mugitty** [comment]
@kltm, as the rules are implemented, they will be included as part of the standard suite of tests in the pipeline

**Comment by pgaudet** [comment]
Tests for implemented GORULES: 

- [ ] [GORULE:0000001](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000001.md)
- [ ] [GORULE:0000002](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000002.md)
- [ ] [GORULE:0000006](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000006.md)
- [ ] [GORULE:0000008](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000008.md)
- [ ] [GORULE:0000011](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000011.md)
- [ ] [GORULE:0000013 - Taxon constraints](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000013.md) - approved but cannot be tested since it is not implemented in onto-bio
- [ ] [GORULE:0000015 - Dual species check](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000015.md)
- [ ] [GORULE:0000016 - IC required a with/from value](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000016.md)
- [ ] [GORULE:0000017 - with/from not allowed with IDA](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000017.md)
- [ ] [GORULE:0000018 - with/from mandatory with IPI](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000018.md)

**Comment by pgaudet** [comment]
* [GAF tests](https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf)
* [GPAD tests](https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gpad)

**Comment by pgaudet** [comment]
Test summary is here: https://docs.google.com/spreadsheets/d/1rCc2UL1IDDpyqc3Lp-Wuu9onzbWCeySEBfq59o4_0KI/edit?gid=552959064#gid=552959064

GAFs are passing tests
GPAD is not yet tested because the pipeline doesn't produce any files that adhere to GPAD2.0 specs. To do when the GPAD output is fixed.
