### ISSUE TITLE
Add a GO Rule to ensure that no bioRxiv references used for evidence are more than 1 or 2 years old

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#998]
As discussed on 2019-02-13 call, while we would allow the use of bioRxiv articles as evidence, none than one or two years (TBD) would be allowed unless they were "updated" with a new date or examined and updated with the final publication information.

**Comment by pgaudet** [comment]
@mugitty Can we query to check whether this prefix has ever been used?

**Comment by mugitty** [comment]
@pgaudet , I need to see if it is possible to query solr and search by db field.  Else, I would have to create a script to pull out the gaf files from http://current.geneontology.org/annotations/index.html and search db field = bioRxiv . Even if there are no current violations, they can be added in the future. Gorules should be modified to check for this database, the flag and remove as necessary.

**Comment by cmungall** [comment]
I think this issue is now irrelevant. NIH funded biorxiv preprints now get PMCIDs and PMIDs
https://www.ncbi.nlm.nih.gov/pmc/about/nihpreprints/

It would still be possible to use eutils to determine if a PMID is for a preprint or not, but I suggest the value of this check will be negligible in terms of quality control, but I defer to @pgaudet

Other literature queries are more important e.g

- #676

**Comment by pgaudet** [comment]
I will remove biorxiv from the dbxrefs, to make sure these are not used. 

Thanks !

**Comment by pgaudet** [comment]
Removed 

- database: bioRxiv
  name: bioRxiv
  synonyms:
    - BIORXIV
  generic_urls:
    - https://www.biorxiv.org/
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      id_syntax: '[0-9]+'
      url_syntax: https://www.biorxiv.org/content/[example_id]
      example_id: bioRxiv:10.1101/530881v2
      example_url: https://www.biorxiv.org/content/10.1101/530881v2
