### ISSUE TITLE
Drop in number relations in go-plus.json file

### ISSUE THREAD

**Issue by alexsign** [geneontology/go-site#999]
There is about 3000 term relations less in the new 
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json
total of 94974 compare to 97904 one from 13th of February. 
Please confirm that this is intentional removal.

**Comment by cmungall** [comment]
@ukemi @balhoff regulates inferences?

**Comment by balhoff** [comment]
I don't think we've made any changes related to that yet.

**Comment by ukemi** [comment]
Shouldn't be. I don't think we have implemented that. I am still going through the big QC file.

**Comment by cmungall** [comment]
Note there was a large change in numbers of each type, with has_input, has_output, has_participant being selectively replaced with more specific relations. But there should be no overall drop

**Comment by ukemi** [comment]
That makes sense.

**Comment by alexsign** [comment]
Does anyone still looking into this or 3000 relations gone for good?

**Comment by ukemi** [comment]
Hopefully this will be fixed as part of this work.
https://github.com/geneontology/helpdesk/issues/192

**Comment by alexsign** [comment]
@ukemi thanks

**Comment by balhoff** [comment]
@alexsign please take a look at the `2019-02-21` version; hopefully this is fixed.

**Comment by ukemi** [comment]
They are back in both of the obo files this morning. Once we hear back from @alexsign we can close this.

**Comment by alexsign** [comment]
@balhoff @ukemi It looks much better now, but I still have 1338 less compare to what is in the database before initial hiccup.

**Comment by alexsign** [comment]
here is the head of the file with missing relations. I can send full list by email if you like.
CHILD_ID        PARENT_ID       RELATION_TYPE
GO:0000053      GO:0072350      I
GO:0000096      GO:0006520      I
GO:0000097      GO:0008652      I
GO:0000098      GO:0009063      I
GO:0000105      GO:0009073      I
GO:0000105      GO:0018130      I
GO:0000105      GO:1901607      I
GO:0000452      GO:0016074      I
GO:0000454      GO:0016074      I
GO:0000951      GO:0044272      I

**Comment by ukemi** [comment]
Hi @alexsign,

I assume these were all subclass relationships? I looked at the first one.

CHILD_ID PARENT_ID RELATION_TYPE
GO:0000053 (argininosuccinate metabolic process)  is_a GO:0072350 (tricarboxylic acid metabolic process)I 

This is no longer inferred by the reasoner. It is an alpha-amino acid metabolic process and a cellular modified amino acid metabolic process. (N(omega)-L-arginino)succinic acid is not a tricarboxylic acid in ChEBI. So this one looks ok. But being the worrier that I am, I would like to do more than just look at the first one in the list.

@balhoff is there any way we can get this list and do a sanity check with respect to the ChEBI structure to make sure that they are no longer inferred? Assuming we only replaced the inferred relationships with this change, this might be ok. It might be nice to also have the list with the term names so that we can take a manual look. There curator in me is always present.

**Comment by alexsign** [comment]
@ukemi @balhoff here is the full list
[missing_relations.txt](https://github.com/geneontology/go-site/files/2894629/missing_relations.txt)

**Comment by ukemi** [comment]
Thanks @alexsign !

It looks like these are all subclasses except one. I wonder if they were all originally asserted and when @cmungall made his changes he removed them. If this is the case then I think this is ok because we should be classifying these based on ChEBI. The exception to this is if we have elucidated a pathway explicitly in GO and we have manually determined that it has more than one type of primary input or output. I'm not sure how to check that automatically, but maybe the conservative approach would be to add them back for now and then vet them.

**Comment by ukemi** [comment]
Hmmm. The plot thickens. I'm not sure why arginosuccinate is not a tricarboxylic acid, but I don't see it in ChEBI.

**Comment by ukemi** [comment]
For the one part_of relationship, it is between GO:0099504 (synaptic vesicle endosomal processing)  and GO:0099504 (synaptic vesicle cycle). I think this was a manual change made independent of the new relations.

**Comment by ukemi** [comment]
GO:0002148  (hypochlorous acid metabolic process) is_a GO:0072593 (reactive oxygen species metabolic process) should be inferred. According to ChEBI, CHEBI:24757 (hypochlorous acid) is_a reactive oxygen species CHEBI:26523.

**Comment by ukemi** [comment]
I think I figured this out! @cmungall and @balhoff , I'm pretty sure we need to change the relation or add relations to the GCIs.

'has output' some 'hypochlorous acid' EquivalentTo 'has output' some hypochlorite

We need to add ones like this:
'has primary output' some 'hypochlorous acid' EquivalentTo 'has primary output' some hypochlorite

**Comment by balhoff** [comment]
I've updated owltools with the new relations; now need to get it into a new docker image: https://github.com/INCATools/ontology-development-kit/issues/179

**Comment by ukemi** [comment]
Last night and this morning, I changed the logical defs of a bunch of terms that should classify as metabolic processes. I am continuing that work. Once I am done, we can have another look at the diff file to see if we have missed anything. I am hoping that the combination of @balhoff and my work will correct this.

**Comment by balhoff** [comment]
The new owltools should be in use for the snapshot release tonight, Feb. 26. It takes a while to run though, so the result would probably not be available until Feb. 28, UK time.

**Comment by alexsign** [comment]
@ukemi @balhoff thanks guys for looking into this. once its done our pipeline will pick it up automatically, but I'll let you know.

**Comment by ukemi** [comment]
Thanks @alexsign. There may be a few stragglers that I miss by hand, so your results will help me find them. I suspect some differences will be valid due to changes in ChEBI etc, but we will check that.

**Comment by balhoff** [comment]
@alexsign please take a look at the lates snapshot (2019-02-27).

**Comment by alexsign** [comment]
Thanks @balhoff relations looks good now. I have another issue with cross product relation changes for CHEBI mostly from "has_output" to "has_primary_output", but I guess it's expected.

**Comment by pgaudet** [comment]
We should definitely announce this !!! Will it go out in this upcoming release? Don't we need to give people some more time ? 

@suzialeksander 
@cmungall 
@thomaspd

**Comment by ukemi** [comment]
Hi @alexsign, Yes the new relations are deliberate, we introduced them so that we could identify primary participants in metabolic reactions and distinguish them from intermediates and inputs that weren't necessarily being metabolized, like ADP and NAD. We will continue to review some relationships by hand this morning, but this is just part of regular ontology maintenance.

**Comment by ukemi** [comment]
Note that there were three kinds of changes to relationships:

1. 'has participant' to 'has primary input or output' for general metabolism
2. 'has input' to 'has primary input' for catabolic processes
3. 'has output' to 'has primary output' for biosynthetic processes

**Comment by alexsign** [comment]
Thanks @ukemi, I added changes to out database. I'm closing this ticket.
